Update fine-grain.adoc
keycloak/keycloak-documentation pull request #1019
Opened 2020-08-23 07:46 UTC by PoojaChandak

Observed a few changes, suggesting the same. Kindly check.

2020-09-03 13:00 UTC, PoojaChandak commented
Hi, these are minor typo/grammatical change suggestions. Kindly check and let me know if any updates required.

2020-09-03 13:17 UTC, stianst requested changes
Thanks, one minor thing to change then this is good to go

2020-09-03 13:17 UTC, stianst commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +Another thing you might want to do is to restrict the set roles an admin is allowed
```suggestion
Another thing you might want to do is to restrict the set of roles an admin is allowed
```

2020-09-03 13:32 UTC, PoojaChandak commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +Another thing you might want to do is to restrict the set roles an admin is allowed
Review comment update added. Kindly check.

2020-09-07 13:09 UTC, stianst approved these changes

2020-09-07 13:09 UTC, merged