Updating IBM Power in release note
keycloak/keycloak-documentation pull request #1043
Opened 2020-10-05 08:23 UTC by rahsin11

2020-10-27 07:18 UTC, rahsin11 commented
@andymunro Can you please review these changes for Power arch.

2020-10-27 15:15 UTC, SNiemann15 commented on release_notes/topics/product/7_4_final.adoc
> +{project_name} for IBM Z/IBM Power is supported only in the OpenShift environment. Bare metal installations on IBM Z/IBM Power are not supported.
@rahsin11 Please use correct brand names:  IBM Z and IBM Power Systems

{project_name} for IBM Z and IBM Power Systems is supported only in the OpenShift environment. Bare metal installations on IBM Z and IBM Power Systems are not supported.

2020-10-27 15:16 UTC, SNiemann15 commented on topics/templates/document-attributes-product.adoc
> +:openshift_openj9_platforms: IBM Z/ IBM Power
IBM Z/IBM Power Systems

2020-10-27 20:59 UTC, andymunro submitted a review, later dismissed
This looks good. Thanks

2020-10-28 09:20 UTC, rahsin11 commented
I made the changes as per @SNiemann15 review and squashed the commits. @andymunro can it be merged now.

2020-10-30 18:35 UTC, andymunro commented
@pskopek Can this be merged now. It is a very small change.

2020-11-10 21:18 UTC, andymunro commented
@abstractj or @hmlnarik can you approve this and merge it?

2020-11-12 15:29 UTC, hmlnarik requested changes
This PR is missing JIRA. @rahsin11 / @andymunro Please file a JIRA and update the PR.

2020-11-12 15:45 UTC, rahsin11 commented
> This PR is missing JIRA. @rahsin11 / @andymunro Please file a JIRA and update the PR.

2020-11-12 15:48 UTC, rahsin11 commented
I have updated the JIRA in the PR @hmlnarik

2020-11-12 18:51 UTC, merged