KEYCLOAK-16072 add mising Advanced Login Configuration documentation
keycloak/keycloak-documentation pull request #1053
Opened 2020-10-26 18:00 UTC by pA1nD

Add missing sections in docs for `Keycloak.prototype.redirectToLogin`

2020-11-09 15:21 UTC, andymunro commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +By default, all unauthorized requests will be redirected to the Keycloak login page unless your client is bearer-only.
Change Keycloak to {project_name}

2020-11-09 15:21 UTC, andymunro commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +For example, this override checks if the url contains /api/ and disables login redirects:
Always use URL instead of url

2020-11-09 15:21 UTC, andymunro requested changes
Two changes requested.

2020-11-13 22:37 UTC, andymunro approved these changes

2021-02-17 18:47 UTC, andymunro commented
@hmlnarik Would you be able to approve this change?

2021-03-23 14:09 UTC, andymunro commented
@mposolda Does this look okay to you?

2021-05-03 16:14 UTC, abstractj approved these changes

2021-05-03 16:14 UTC, abstractj approved these changes

2021-05-03 16:14 UTC, merged