KEYCLOAK-9551 Client Credentials Grant should not generate refresh token
keycloak/keycloak-documentation pull request #1055
Opened 2020-11-05 16:37 UTC by mposolda

2020-11-05 16:39 UTC, mposolda commented
Codebase PR: https://github.com/keycloak/keycloak/pull/7569

2020-11-05 16:43 UTC, pedroigor submitted a review, later dismissed

2020-11-05 22:44 UTC, andymunro commented on server_admin/topics/clients/oidc/service-accounts.adoc
> +There is only access token returned by default. There is no refresh token returned and there is also no user session created
add "the" before "only"

2020-11-05 22:45 UTC, andymunro commented on server_admin/topics/clients/oidc/service-accounts.adoc
> +on {project_name} side upon successful authentication by default. Due the lack of refresh token, there is a need to re-authenticate when access token expires,
add "the" before "{project_name}"

2020-11-05 22:46 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +From this {project_name} version, the OAuth2 Client Credentials Grant endpoint does not issue refresh tokens by default. This behaviour is aligned with the OAuth2 specification.
we use the american English spelling "behavior"

2020-11-05 22:46 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +in improved performance and memory consumption. Clients, which use Client Credentials Grant are encouraged to stop using
no comma after Clients

2020-11-05 22:47 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +For the backwards compatibility, there is a possibility to stick to the behaviour of old versions. When this is used, refresh token will be still issued after
behavior

2020-11-05 22:48 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +For the backwards compatibility, there is a possibility to stick to the behaviour of old versions. When this is used, refresh token will be still issued after
Add "the" before "refresh token"

2020-11-05 22:48 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +successful authentication with Client Credentials Grant and also the user session will be created. This can be enabled for the particular client in
"a" successful
and "the" before "Client Credentials  Grant"

2020-11-05 22:49 UTC, andymunro requested changes
Approved with a few comments. I will be out on PTO Friday.

2020-11-06 08:08 UTC, mposolda commented
@andymunro I've applied all your recommendations. Thanks for the review!

2020-11-06 08:16 UTC, merged