Add jwks_uri to list of endpoints (Spring OAuth2)
keycloak/keycloak-documentation pull request #1056
Opened 2020-11-08 09:46 UTC by dxmann73

When configuring Spring OAuth2, we need the jwk-set-uri for the provider. Needed some digging to find it, so I thought I'd add this information here.

2020-11-09 15:11 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +_/auth_:  i.e. $$https://localhost:8080/auth$$.
In general please replace "i.e" with "that is" and replace "e.g." with "for example"

However in this case, please use "for example"

2020-11-09 15:12 UTC, andymunro requested changes
One change requested

2020-11-10 08:54 UTC, dxmann73 commented
Thanks for the suggestion! Changed as requested.

2021-02-17 12:29 UTC, stianst approved these changes

2021-02-17 12:29 UTC, merged