KEYCLOAK-15955 Implement a pluggable Upgrade strategy
keycloak/keycloak-documentation pull request #1062
Opened 2020-11-20 16:23 UTC by vmuzikar

2020-11-23 07:09 UTC, slaskawi requested changes
LGTM, @andymunro May I kindly ask you to review and merge this one?

2020-11-23 07:51 UTC, vmuzikar commented
In the latest force-push I've fixed the failing tests.

2020-11-23 16:56 UTC, andymunro commented on server_installation/topics/operator/upgrading.adoc
> +  ensures a zero-downtime upgrade but is more suitable for minor version upgrades that don't require database migration
Avoid contractions.  Change "don't" to "do not"

2020-11-23 16:57 UTC, andymunro requested changes
Looks good, Sebastian. Just one comment.

2020-11-24 10:35 UTC, vmuzikar commented
@andymunro Thanks for the review! Fixed.

2020-12-03 10:59 UTC, vmuzikar commented
The test failure is unrelated to this.

2021-06-09 10:03 UTC, vmuzikar commented
Rebased to resolve conflicts.
@andymunro Could we please merge this?

2021-06-09 10:30 UTC, stianst approved these changes

2021-06-09 10:31 UTC, stianst commented
Approving based on previous reviews from Andy and Sebastian

2021-06-09 10:31 UTC, merged