Usage of default value in ${…​} enclosure
keycloak/keycloak-documentation pull request #1132
Opened 2021-03-04 07:22 UTC by tlappe

You can set a default value in keycloak.json with ${...} but documentation is missing.

2021-11-10 10:27 UTC, stianst commented
@andymunro from a technical perspective this looks good, but can you review it as well?

2021-11-10 10:27 UTC, stianst approved these changes

2021-12-09 14:39 UTC, andymunro commented on securing_apps/topics/oidc/java/java-adapter-config.adoc
> +Replacement of environment variables is also supported via the `env` prefix, e.g. `${env.MY_ENVIRONMENT_VARIABLE}`. You can also define a default value `${...:default_value}` which is used if the sys
Add a comma before which.

2021-12-09 14:39 UTC, andymunro requested changes
One change needed

2021-12-09 14:39 UTC, andymunro commented
@tlappe To fix the Waiting for Status problem, use this command: git pull upstream main

2023-03-09 15:03 UTC, ahus1 commented
As this PR has been abandoned, this is now superseded by #1795

2023-03-09 15:03 UTC, closed without merging