KEYCLOAK-16729 Add more info for how to retrieve provider types
keycloak/keycloak-documentation pull request #1137
Opened 2021-03-15 17:16 UTC by mposolda

@andymunro Do you please have a chance to review?

2021-03-15 18:50 UTC, andymunro commented on server_development/topics/providers.adoc
> +In your provider implementation, you can use other providers available in the {project_name}. The existing providers can be typically retrieved with the
remove "the" before " {project_name}"

2021-03-15 18:50 UTC, andymunro commented on server_development/topics/providers.adoc
> +usage of the `KeycloakSession`, which is available to your provider as described <<_implementing_spi,above>>.
described in

2021-03-15 18:51 UTC, andymunro commented on server_development/topics/providers.adoc
> +* *Single-implementation provider types* - There can be only single active implementation of the particular provider type in the {project_name} runtime.
remove "the" before " {project_name}"

2021-03-15 18:52 UTC, andymunro commented on server_development/topics/providers.adoc
> +Hence there can be only single implementation of this provider active for the {project_name} server. If there are multiple provider implementations available to the server runtime,
add "a" before "single"

2021-03-15 18:54 UTC, andymunro commented on server_development/topics/providers.adoc
> +* *Multiple implementation provider types* - Those are provider types, which allow to have multiple implementations available and working together
Change ", which allow to have" to "that allow"

2021-03-15 18:54 UTC, andymunro commented on server_development/topics/providers.adoc
> +that particular event can be sent to all the listeners (jboss-logging, sysout etc). In the code, you can obtain specified instance of the provider
a specified

2021-03-15 18:55 UTC, andymunro commented on server_development/topics/providers.adoc
> +for example like `session.getProvider(EventListener.class, "jboss-logging")` . You need to specify `provider_id` of the provider as the second argument
chnage "like" to "such as"   -- in all cases

Add "the" after "specify"

2021-03-15 18:56 UTC, andymunro requested changes
Looks good.  Minor changes, Marek

2021-03-16 08:46 UTC, mposolda commented
@andymunro I've applied all your suggestions. Thanks!

2021-03-16 08:46 UTC, merged