KEYCLOAK-17491 Move the key settings to the new Keys tab
keycloak/keycloak-documentation pull request #1143
Opened 2021-03-22 05:30 UTC by y-tabata

Code PR: https://github.com/keycloak/keycloak/pull/7874

2021-05-19 10:23 UTC, mposolda approved these changes, later dismissed
@y-tabata Thanks, These changes look good to me. However the PR needs to wait to be merged with the related codebase PR https://github.com/keycloak/keycloak/pull/7874 .

Also rebase is needed. Maybe you can just remove the file "client-scopes-evaluate.png" from this PR? If the only reason to include this file is the new "Keys" tab, then it is completely fine to remove the file "client-scopes-evaluate.png" from this PR (The tab at the top does not need to be 100% accurate in the docs screenshots as long as the "main content" itself as accurate.

@andymunro Do you have a chance to review this please?

2021-05-19 12:29 UTC, andymunro commented on server_admin/topics/clients/client-oidc.adoc
>  * set ON to `JWKS URL` switch
toggle JWKS URL to ON

2021-05-19 12:29 UTC, andymunro requested changes
Looks good.  Just one change.

2021-05-21 06:29 UTC, y-tabata commented on server_admin/topics/clients/client-oidc.adoc
>  * set ON to `JWKS URL` switch
@andymunro Changed.

2021-05-21 06:30 UTC, y-tabata commented
@mposolda @andymunro Thanks for reviewing. I rebased and changed according to your comment.

2021-05-27 13:27 UTC, mposolda approved these changes
@y-tabata @andymunro Thanks

2021-05-27 13:27 UTC, merged