KEYCLOAK-17330 Document how to use private extensions
keycloak/keycloak-documentation pull request #1147
Opened 2021-03-31 19:45 UTC by apeschel

Relies on https://github.com/keycloak/keycloak-operator/pull/340

Adds instructions on how to use HTTP basic auth URLs to access private extensions.

2021-11-10 11:13 UTC, vmuzikar reviewed
@iankko Could you please confirm RH-SSO init container officially supports HTTP auth?

This needs to be merged after https://github.com/keycloak/keycloak-operator/pull/389.

2021-12-06 16:09 UTC, andymunro approved these changes

2021-12-09 14:36 UTC, andymunro commented
@apeschel To fix the Waiting for Status problem, use this command: git pull upstream main

2021-12-09 14:37 UTC, andymunro requested changes
To fix the Waiting for Status problem, use this command: git pull upstream main

2021-12-13 22:49 UTC, apeschel commented
@andymunro Just updated it

2021-12-14 13:22 UTC, andymunro reviewed
Thanks, @apeschel.  I am not sure why you are still getting the message about Waiting for status ..  Usually it is fixed by:  git pull upstream main

@pskopek Do you have any ideas?

2021-12-16 00:58 UTC, apeschel commented
@andymunro On my side it says it's waiting for a maintainer to approve the run. Just updated it again.

2023-03-09 15:10 UTC, ahus1 commented
Hi @iankko - there is still an open question on this PR. Can you answer this question, or should this PR rather be closed? Thanks!

> @iankko Could you please confirm RH-SSO init container officially supports HTTP auth?

2023-03-09 15:15 UTC, ahus1 commented
@iankko - update: I'm closing this PR as it relates to a PR for the old operator which has not been merged.

2023-03-09 15:15 UTC, closed without merging