KEYCLOAK-17693 add config for loading custom IdMapper class
keycloak/keycloak-documentation pull request #1151
Opened 2021-04-12 03:28 UTC by Yang-Xie-OSS

The documentation of PR [KEYCLOAK-17693](https://github.com/keycloak/keycloak/pull/7921).
And this is the [JIRA](https://issues.redhat.com/browse/KEYCLOAK-17693) link.

2021-07-23 07:17 UTC, mposolda approved these changes, later dismissed
@Yang-Xie-OSS Thanks! I am approving. IMO this can be merged once the codebase is merged (which depends on the tests).

@andymunro Do you please have a chance to review this?

2021-07-23 16:08 UTC, andymunro commented on securing_apps/topics/oidc/java/servlet-filter-adapter.adoc
> +If you need to customize the session ID mapper you can configure the fully qualified name of the class in the Filter init-param keycloak.config.idMapper. Session ID mapper is a mapper which is used t
comma after an introductory clause -- after mapper,
"is a mapper that..." - use "that' not "which" when the rest of the sentence qualifies the noun, meaning it is the specific mapper "that" is used to map user IDs and session IDs.

2021-07-23 16:08 UTC, andymunro requested changes
Some minor changes.

2021-07-26 05:53 UTC, Yang-Xie-OSS commented
@andymunro 
Thanks for the review. I've edited it.

2021-08-03 15:44 UTC, mposolda approved these changes

2021-08-03 15:45 UTC, merged