KEYCLOAK-17861 email notification for add/remove group
keycloak/keycloak-documentation pull request #1158
Opened 2021-04-26 07:38 UTC by cgeorgilakis

2021-12-09 14:25 UTC, andymunro commented on server_admin/topics/groups.adoc
> +User is notified via email every time he is added to/ removed from a group.
Avoid latin words such as "via" and gender-based words such as "he"

Suggested:  The user is notified by email when that user is added to or removed from a group.

2021-12-09 14:26 UTC, andymunro requested changes
One change suggested.

2021-12-09 14:31 UTC, andymunro commented
@cgeorgilakis You will need to use this command to fix the verification build
git pull upstream main

2021-12-10 14:43 UTC, cgeorgilakis commented
I have rebased from keycloak main and have applied your proposal to new proc-managing-groups.adoc

2021-12-10 15:33 UTC, andymunro approved these changes

2023-03-20 09:06 UTC, ahus1 commented
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Please include these documentation changes into the main pull request.

Thanks!

2023-03-20 09:06 UTC, closed without merging