KEYCLOAK-17995 Document manual migration step for Keycloak 13 upgrade
keycloak/keycloak-documentation pull request #1165
Opened 2021-05-05 09:47 UTC by mhajas

2021-05-05 14:58 UTC, hmlnarik requested changes

2021-05-05 14:58 UTC, hmlnarik commented on upgrading/topics/keycloak/changes.adoc
> +Manual migration step needed::
This needs to be first entry in the chapter on Migrating to 13.0.0

2021-05-05 14:58 UTC, hmlnarik commented on upgrading/topics/keycloak/changes.adoc
> +Manual migration step needed::
```suggestion
==== Manual migration step needed
```

2021-05-05 14:58 UTC, hmlnarik commented on upgrading/topics/keycloak/changes.adoc
> +  remove following lines from the configuration file.
Manual change is required when the standalone.xml contains references to any of the SmallRye modules.
SmallRye modules were removed from the underlying {appserver_name} distribution, and the server does not start
if the configuration references them. Thus if the configuration in the `standalone.xml` refers to these modules,
the server configuration migration via `migrate-standalone.cli` fails before any changes are made to the configuration.
In such case, to perform server configuration migration, you have to manually remove all the lines that refer
to SmallRye modules. In the default configuration, you need to remove specifically the following lines:

2021-05-05 15:38 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +  The keycloak migration script does not work out of the box after removal of SmallRye dependencies from the Wildfly container. Therefore,
always change "out of the box" to "by default"

2021-05-05 15:39 UTC, andymunro requested changes
Looks good, @hmlnarik.  Only one change requested.

2021-05-05 15:41 UTC, mhajas commented
Thanks @hmlnarik @andymunro I updated the text.

2021-05-05 15:49 UTC, andymunro approved these changes
Perfectly written and very clear, @hmlnarik

2021-05-05 15:51 UTC, hmlnarik approved these changes
Thank you for your contribution!

2021-05-06 07:06 UTC, hmlnarik commented
Related PR: keycloak/keycloak#7997

2021-05-06 09:40 UTC, merged