KEYCLOAK-16616 authenticationSessions map in RootAuthenticationSessio…
keycloak/keycloak-documentation pull request #1190
Opened 2021-05-31 13:32 UTC by martin-kanis

…nEntity grows unboundedly

2021-05-31 13:34 UTC, martin-kanis commented
@mhajas @andymunro This piece of documentation is needed for Keycloak 14. If you could review it that would be great. Thanks!

2021-05-31 14:33 UTC, mhajas reviewed
Thank you for the PR @martin-kanis. I am missing some introduction to the issue. Should we briefly add something about what types of sessions Keycloak have and when it is created and what it is causing when there is too many authenticationSessions? And then continue with mitigations for RootAuthenticationSession and then authenticationSession? Or we assume that the reader knows this already?

2021-05-31 16:00 UTC, martin-kanis commented
> Thank you for the PR @martin-kanis. I am missing some introduction to the issue. Should we briefly add something about what types of sessions Keycloak have and when they are created and what it is causing when there is too many authenticationSessions? And then continue with mitigations for RootAuthenticationSession and then authenticationSession? Or we assume that the reader knows this already?

This kind of introduction would probably belong to a different section than "Threat Mitigation" (Not sure where though). However I slightly expanded the description of auth sessions, threats and I also mentioned that it affects only deployments that use infinispan provider for auth sessions.

2021-06-01 06:47 UTC, mhajas approved these changes, later dismissed
Thanks, @martin-kanis, this is exactly what I imagined.

2021-06-03 08:35 UTC, mhajas submitted a review, later dismissed

2021-06-04 15:09 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +{project_name} creates an authentication session for each authentication request within a realm. This session is internally represented by `RootAuthenticationSession`. Each `RootAuthenticationSession
Add a comma before "the browser session"
Remove the 's after browser

2021-06-04 15:17 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +Higher memory usage and a network overload in a cluster may occur for deployments where there's many active `RootAuthenticationSession` with a lot of authentication sessions.
change "there's" to "there are"

2021-06-04 15:19 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +There's a possibility to mitigate the aforementioned threats. The maximum allowed number of `RootAuthenticationSession` should be addressed by limiting the request rate per time on the proxy or load
Change "There's" to "There is"

2021-06-04 15:21 UTC, andymunro requested changes
A few changes

2021-06-07 12:52 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +NOTE: This section describes deployments that use the infinispan provider for authentication sessions.
```suggestion
NOTE: This section describes deployments that use the `{jdgserver_name}` provider for authentication sessions.
```

2021-06-10 07:00 UTC, hmlnarik approved these changes

2021-06-10 07:00 UTC, merged