KEYCLOAK-16616 Release notes for limiting number of auth sessions
keycloak/keycloak-documentation pull request #1193
Opened 2021-06-03 08:20 UTC by martin-kanis

@andymunro Here is a release note for https://github.com/keycloak/keycloak-documentation/pull/1190

2021-06-04 15:27 UTC, andymunro commented on release_notes/topics/14_0_0.adoc
> +* Support for configuring maximum number of active authentication sessions. Default value is set to 300 authentication sessions (browser's tabs) per a browser's session
Add The before Support and Default
Remove 's before tabs

2021-06-04 15:27 UTC, andymunro requested changes
a few changes

2021-06-10 06:57 UTC, hmlnarik approved these changes, later dismissed

2021-06-10 07:24 UTC, hmlnarik approved these changes

2021-06-10 07:25 UTC, merged