KEYCLOAK-18738 Improve RootAuthenticationSession description
keycloak/keycloak-documentation pull request #1236
Opened 2021-07-27 14:49 UTC by martin-kanis

2021-07-28 13:35 UTC, hmlnarik requested changes
Thank you for the PR! Please see inline for comments.

2021-07-28 13:35 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +`RootAuthenticationSessionEntity` as a collection of `AuthenticationSessionEntity`. {project_name} stores authentication sessions in a dedicated {jdgserver_name} cache.
```suggestion
`RootAuthenticationSessionEntity` as a collection of `AuthenticationSessionEntity` objects. {project_name} stores authentication sessions in a dedicated {jdgserver_name} cache.
```

2021-07-28 13:35 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +
```suggestion

[[_limit-authentication-sessions]]
```


Also add this anchor to sticky sessions in the installation guide:
```
[[_sticky-sessions]]
```

2021-07-28 13:35 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +Higher memory usage and a network overload in a cluster may occur for deployments where there are many active `RootAuthenticationSessionEntity` with a lot of `AuthenticationSessionEntity`.
```suggestion
Higher memory usage may occur for deployments where there are many active `RootAuthenticationSessionEntity` with a lot of `AuthenticationSessionEntity`.

If the load balancer does not support or is not configured for 
link:{installguide_link}#_sticky-sessions[session stickiness], the network over in a cluster can
increase significantly. The reason for this load is that each request that lands to a node which does not own
the appropriate authentication session needs to retrieve and update the authentication session record in the owner
node which involves a separate network transmission for both the retrieval and the storage.
```

2021-07-28 13:35 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +Authentication requests can come from any type of clients e.g. Admin CLI. In that case a new authentication session is also created with one authentication sub-session.
```suggestion
Authentication requests can come from any type of clients e.g. Admin CLI. In that case a new authentication session is also created with one authentication sub-session.      
Please note that authentication sessions can be created also in other ways than via a browser flow. The text below
is applicable regardless of the source flow.

```

2021-07-28 13:35 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +
```suggestion

The number of maintained `RootAuthenticationSessionEntity` objects corresponds to the number 
of unfinished login flows from the browser. To keep the number of `RootAuthenticationSessionEntity` 
under control, using an advanced firewall control to limit ingress network traffic is recommended.
```

2021-07-28 19:28 UTC, hmlnarik approved these changes

2021-07-28 19:29 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +
@martin-kanis Has the second part been addressed?

2021-07-28 19:30 UTC, hmlnarik commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +
Ah, I see, it has :)

2021-07-28 20:39 UTC, hmlnarik submitted a review, later dismissed
Thanks for the PR!

2021-07-29 14:42 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +Authentication requests can come from any type of clients e.g. Admin CLI. In that case a new authentication session is also created with one authentication sub-session.
Change "e.g" to ", such as the"
Add a comma after "in that case,"

2021-07-29 14:43 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +Please note that authentication sessions can be created also in other ways than via a browser flow. The text below is applicable regardless of the source flow.
Change "via" to "using"

2021-07-29 14:44 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +number of stored `RootAuthenticationSessionEntity` and by number of `AuthenticationSessionEntity` within each `RootAuthenticationSessionEntity`.
add "the" before number in both cases

2021-07-29 14:51 UTC, andymunro commented on server_admin/topics/threat/auth-sessions-limit.adoc
> +increase significantly. The reason for this load is that each request that lands to a node which does not own the appropriate authentication session needs to retrieve
Change "lands to a node which" to "lands on a node that"
Always use "that" when the remainder of the sentence qualifies the first part the sentence.
Use "which" when the remainder of the sentence provides additional information, but does not qualify the first part of the sentence.

2021-07-29 14:52 UTC, andymunro requested changes
A few changes, Hynek.

2021-07-29 18:36 UTC, martin-kanis commented
@andymunro Thank you Andy. I included your suggestions.

2021-07-29 19:17 UTC, hmlnarik approved these changes
Thank you @martin-kanis and @andymunro!

2021-07-29 19:17 UTC, merged