KEYCLOAK-18939 Release notes for 15.0.1
keycloak/keycloak-documentation pull request #1242
Opened 2021-08-04 12:59 UTC by mposolda

2021-08-04 14:27 UTC, andymunro commented on release_notes/topics/15_0_1.adoc
> +This release contains some important bugfixes. In addition, We would like to Thank You to https://github.com/leandrobortoli[Leandro José de Bortoli] for his contributions to the
bug fixes
Change "Thank You to" to "thank"

2021-08-04 14:27 UTC, andymunro commented on release_notes/topics/15_0_1.adoc
> +FAPI related functionalities like JARM support and improvements in CIBA.
Always change "like" to "such as"

2021-08-04 14:28 UTC, andymunro requested changes
A few minor changes, Marek.

2021-08-05 14:14 UTC, mposolda commented on release_notes/topics/15_0_1.adoc
> +FAPI related functionalities like JARM support and improvements in CIBA.
My favourite mistake :(  Hopefully one day, I will be able to get it right :)

2021-08-05 14:15 UTC, mposolda commented
@andymunro Applied all your suggestions. Thanks!

2021-08-05 14:32 UTC, merged