KEYCLOAK-19348 SAML/ OIDC IdP AutoUpdate
keycloak/keycloak-documentation pull request #1251
Opened 2021-09-22 09:41 UTC by cgeorgilakis

2021-12-08 22:43 UTC, andymunro commented on server_admin/topics/identity-broker/autoupdated.adoc
> +SAML and OIDC Identity Providers can be configured to automatically updated from its metadata URL (during Identity Provider creation and update).
add "be" before "updated"
change "its" to "their"

2021-12-08 22:44 UTC, andymunro commented on server_admin/topics/identity-broker/autoupdated.adoc
> +Autoupdate field was added (default value false). When autoupdate is true, realm admin must fulfill Refresh period field( default 1 day).
add "the" before 3 occurrences of "realm admin"

2021-12-08 22:45 UTC, andymunro commented on server_admin/topics/identity-broker/autoupdated.adoc
> +For OIDC Identity Provider, realm admin must fulfill Issuer. Metadata URL automatically become equal to issuer + '/.well-known/openid-configuration'.
change "become" to "becomes"

2021-12-08 22:45 UTC, andymunro commented on server_admin/topics/identity-broker/autoupdated.adoc
> +In this case, SAML/OIDC Identity Provider is automatically updated every Refresh period. Last refresh time is automatically filled and shows last Identity Provider autoupdate.
Add "the" before two occurrences of "last"

2021-12-08 22:46 UTC, andymunro requested changes
A few comments. Thanks.

2021-12-09 07:51 UTC, cgeorgilakis commented
I have done proposed changes and rebase to current main branch.

2021-12-09 16:51 UTC, andymunro approved these changes
@cgeorgilakis Thanks for the quick response.

2023-03-20 09:05 UTC, ahus1 commented
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Please include these documentation changes into the main pull request.

Thanks!

2023-03-20 09:05 UTC, closed without merging