[KEYCLOAK-17653] - Front-channel logout
keycloak/keycloak-documentation pull request #1267
Opened 2021-10-08 19:33 UTC by pedroigor

2021-10-08 20:10 UTC, andymunro commented on server_admin/topics/clients/oidc/con-basic-settings.adoc
> +*Front Channel Logout*:: If *Front Channel Logout* is enabled, the application should be able to logout users through the front channel as per link:https://openid.net/specs/openid-connect-frontchanne
"log out"  (since it is a verb

2021-10-08 20:11 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +{project_name} Once the user is redirect to the logout endpoint, {project_name} is going to send logout requests to
delete {project_name}
redirected

2021-10-08 20:13 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +* By being based on `iframes`, front-channel logout might be impacted by Content Security Policies (CSP) and logout requests might be blocked
add a period after blocked.

2021-10-08 20:14 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +using the <<_back-channel-logout-url, Back-Channel Logout URL>>. If not defined, the server is going to fallback to using the <<_admin-url, Admin URL>>.
"fall back" since it is a verb

2021-10-08 20:16 UTC, andymunro commented on server_admin/topics/clients/oidc/con-basic-settings.adoc
> +*Backchannel Logout URL*:: URL that will cause the client to log itself out when a logout request is sent to this realm (via end_session_endpoint). If omitted, no logout request will be sent to the c
Change it to "no logout requests are sent to the client."

2021-10-08 20:18 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +clients to give a chance to them to invalidate their local user sessions, and potentially redirect the user to some URL
change " to give a chance to them to"
TO
"let them"

2021-10-08 20:19 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +Depending on the client configuration, logout requests can be sent to clients either through the front-channel or through the back-channel.
delete "either"

2021-10-08 20:20 UTC, andymunro commented on server_admin/topics/sso-protocols/oidc.adoc
> +To configure clients to receive logout requests through the front-channel, please look at the <<_front-channel-logout, Front-Channel Logout>> client setting. When using this method, there are a few t
elimiinate "please"
change "there are a few things you need to consider:" 
TO
"consider the following:"

2021-10-08 20:21 UTC, andymunro requested changes
Just a few changes.

2021-10-11 20:10 UTC, pedroigor commented
Thanks, @andymunro. PR updated.

2021-10-15 12:49 UTC, mposolda requested changes
@pedroigor Few minor points to this. I am marking as "Request changes" until we clarify the points:
- It will probably worth to mention OIDC frontchannel logout in the release notes for Keycloak 16? WDYT?
- In the "Client Policies" section, it can be a small single line added about logout executor in the list of executors here https://www.keycloak.org/docs/latest/server_admin/index.html#architecture . This is just minor.

2021-10-15 12:59 UTC, pedroigor commented
@mposolda Sure, I'll update the doc.

2021-10-15 14:46 UTC, pedroigor commented
@mposolda Updated the PR. I'm only not sure about the place I should add the new executor, could you please give more details on where this list is located?

2021-10-18 17:45 UTC, mposolda requested changes
@pedroigor Thanks Pedro. Added one small note to release notes.

For client policies, if you go to https://www.keycloak.org/docs/latest/server_admin/index.html and search for the text like `Enforce more secure signature algorithm when client registration` you will see the part of the page where executors are described. Will it worth to add single line about this new executor for logout?

2021-10-18 17:45 UTC, mposolda commented on release_notes/topics/16_0_0.adoc
> +{project_name} now supports https://openid.net/specs/openid-connect-frontchannel-1_0.html[OpenID Connect Front-Channel Logout 1.0].
Small note: Do we want to highlight the contributor, who initiated this effort and adding his github link? See other release notes for various features contributed by community.

2021-10-20 18:29 UTC, pedroigor commented on release_notes/topics/16_0_0.adoc
> +{project_name} now supports https://openid.net/specs/openid-connect-frontchannel-1_0.html[OpenID Connect Front-Channel Logout 1.0].
@mposolda Added reference to the contributor. Thanks.

2021-10-21 06:28 UTC, mposolda approved these changes
@pedroigor Thanks Pedro!

2021-10-21 06:28 UTC, merged