KEYCLOAK-18276 client content screen enhancement
keycloak/keycloak-documentation pull request #1270
Opened 2021-10-14 08:43 UTC by cgeorgilakis

2021-11-18 16:57 UTC, mposolda commented
@cgeorgilakis Do you please have a chance to rebase this PR? Hopefully this should help to fix the conflicts.

@andymunro Do you please have a chance to review this PR?

2021-11-19 22:09 UTC, andymunro commented on server_admin/topics/clients/client-oidc.adoc
> +
remove "the" before "how"

2021-11-19 22:10 UTC, andymunro commented on server_admin/topics/clients/client-saml.adoc
> +URL that the Relying Party Client provides to the End-User to read about the how the profile data will be used.
remove "the" before "how"

2021-11-19 22:10 UTC, andymunro requested changes
Looks good, @cgeorgilakis.  Just a couple of changes needed.

2021-11-22 08:09 UTC, cgeorgilakis commented
@andymunro I have done the requested changes.
@mposolda client documentation format have been changed. I have placed the documentation in the new adoc files.

2021-11-22 11:08 UTC, mposolda approved these changes
@andymunro @cgeorgilakis Thanks to both of you for the review and for the requested changes and updating the documentation!

2021-11-22 11:08 UTC, merged