KEYCLOAK-19144 remove "Installing from the command line" chapter
keycloak/keycloak-documentation pull request #1273
Opened 2021-10-19 09:22 UTC by jonathanvila

https://issues.redhat.com/browse/KEYCLOAK-19144

Remove the chapter suggesting to install from the command line.

2021-10-25 10:41 UTC, vmuzikar requested changes
@jonathanvila I'm really sorry, I miscommunicated this. The chapter of course needs to stay, but it needs to be present only in the Keycloak docs and be removed from the RH-SSO docs. Could you please just wrap it in some `if` instead of removing it (`ifeval::[{project_community}==true]`)? Thank you!

2021-11-01 12:07 UTC, vmuzikar requested changes
I can still see the chapter present in the RH-SSO docs when I build it locally as:
```
mvn clean install -Pproduct -DskipTests
```

2021-11-05 18:58 UTC, andymunro approved these changes

2021-11-08 07:55 UTC, vmuzikar commented on README.md
> +----------------------------------------
Just a nitpick (not a blocker). Why to make this change? Seems unrelated (and even in an unrelated file).

2021-11-08 07:55 UTC, vmuzikar commented on README.md
> +---------------------------------
Just a nitpick (not a blocker). Why to make this change? Seems unrelated (and even in an unrelated file).

2021-11-08 09:47 UTC, jonathanvila commented
It was for forcing the build on github, we can remove those commits, but it
will take more time removing them than leaving as this has no impact on the
result

On Mon, Nov 8, 2021 at 8:55 AM Václav Muzikář ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/keycloak/keycloak-documentation/pull/1273#discussion_r744471485>
> :
>
> > @@ -7,15 +7,15 @@ For more information about Keycloak visit the [Keycloak homepage](http://keycloa
>
>
>  Contributing to Keycloak Documentation
> ---------------------------------------
> +----------------------------------------
>
> Just a nitpick (not a blocker). Why to make this change? Seems unrelated
> (and even in an unrelated file).
> ------------------------------
>
> In README.md
> <https://github.com/keycloak/keycloak-documentation/pull/1273#discussion_r744471521>
> :
>
> >
>  See our [Contributor's Guide](internal_resources/contributing.adoc). The directory also includes a set of templates and other resources to help you get started.
>
>  If you want to file a bug report or tell us about any other issue with this documentation, you are invited to please use our [issue tracker](https://issues.redhat.com/projects/KEYCLOAK/).
>
>
>  Building Keycloak Documentation
> --------------------------------
> +---------------------------------
>
> Just a nitpick (not a blocker). Why to make this change? Seems unrelated
> (and even in an unrelated file).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak-documentation/pull/1273#pullrequestreview-799775572>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOALESTKIP2O7N4FM4YKI3UK567LANCNFSM5GIUXRNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-08 09:56 UTC, vmuzikar approved these changes

2021-11-08 14:00 UTC, merged