KEYCLOAK-19145 remove POSTGRES_HOST and add text to specify the proxy…
keycloak/keycloak-documentation pull request #1274
Opened 2021-10-19 12:59 UTC by jonathanvila

https://issues.redhat.com/browse/KEYCLOAK-19145

Remove the mention of POSTGRES_HOST  and detail the usage of a proxy to connect to the external database.

2021-10-25 10:52 UTC, vmuzikar commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
@jonathanvila I'd rephrase this a bit to make it even more explicit. :)
```suggestion
The {project_operator} will create a Service to connect to the external database, typically `keycloak-postgresql`. This Service points to the actual external database (as specified by `POSTGRES_EXTERNAL_ADDRESS`) and {project_name} then connects to the database through this operator managed service.
```
WDYT?

2021-10-26 16:41 UTC, jonathanvila commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
:+1:

2021-10-27 15:27 UTC, vmuzikar submitted a review, later dismissed
@jonathanvila LGTM, thank you!

@andymunro Could you please review/merge when you have a chance?

2021-10-27 15:54 UTC, andymunro commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
The Operator will create a Service that connects to an external database, such as `keycloak-postgresql`, that connects {project_name} to the Database that contains the IP address or Service name that is specified by the POSTGRES_EXTERNAL_ADDRESS.

2021-10-27 15:55 UTC, andymunro requested changes
Just one change. Thanks, @jonathanvila

2021-10-28 10:27 UTC, jonathanvila commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
:+1:

2021-11-08 16:11 UTC, andymunro submitted a review, later dismissed

2021-11-08 16:16 UTC, vmuzikar commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
@andymunro @jonathanvila The sentence IMHO now have a completely different meaning. E.g. it implies that `keycloak-postgresql` is the name of the external database, not the Service. And the second part of the sentence IMHO doesn't now make much sense, what connects to what. Maybe we could do something like this:

```
The Operator will create a Service named `keycloak-postgresql`. This Service is configured by the Operator to expose the external database based on the content of `POSTGRES_EXTERNAL_ADDRESS`. {project_name} uses this Service to connect to the Database, that means it does not connect to the Database directly but rather through this Service.
```

2021-11-08 16:17 UTC, vmuzikar reviewed
@andymunro @jonathanvila Please see https://github.com/keycloak/keycloak-documentation/pull/1274#discussion_r744881275.

Sorry for the late comment. I just noticed the sentence was rewritten.

2021-11-09 14:41 UTC, andymunro commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
Looks good except "that means" should be "which means"

2021-11-09 14:45 UTC, jonathanvila commented on server_installation/topics/operator/external-database.adoc
> +The Keycloak Operator will create a Service to connect to the external database, tipycally `keycloak-postgresql`, that will connect to Keycloak to the Database, containing the IP or Service name spec
:+1:

2021-11-09 14:46 UTC, vmuzikar approved these changes

2021-11-10 07:23 UTC, merged