Fix token exchange required features
keycloak/keycloak-documentation pull request #1305
Opened 2021-11-16 15:02 UTC by alcidesmig

In https://github.com/keycloak/keycloak-documentation/pull/1186, I misunderstood the feature documentation because of the implicit links.

In this MR, I revert the wrong change and add some details in order to explanate that not all token exchange flows need the `admin_fine_grained_authz` feature.

2021-12-07 17:12 UTC, andymunro approved these changes, later dismissed

2023-03-13 13:28 UTC, ahus1 approved these changes, later dismissed

2023-03-13 14:12 UTC, andymunro commented on securing_apps/topics/token-exchange/token-exchange.adoc
> +In order to use more than the link:#internal-token-to-internal-token-exchange[Internal Token to Internal Token Exchange] flow, you should also enable the `admin_fine_grained_authz` feature. Please, t
```suggestion
To use more than the link:#internal-token-to-internal-token-exchange[Internal Token to Internal Token Exchange] flow, you should also enable the `admin_fine_grained_authz` feature. For details, see  link:{installguide_profile_link}[{installguide_profile_name}]. 
```

2023-03-13 14:12 UTC, andymunro requested changes
Please avoid using "please" which is not used in our documentation.

2023-03-24 08:25 UTC, ahus1 commented
The Keyclaok documentation is now available in the main Keycloak repository, therefore I moved this PR here: https://github.com/keycloak/keycloak/pull/19293

2023-03-24 08:25 UTC, closed without merging