Add example for mapping role names between Keycloak and Spring Boot
keycloak/keycloak-documentation pull request #1348
Opened 2021-12-22 15:07 UTC by little-pinecone

The reason for this PR is the ambiguity regarding the setting of the role name prefix. I've seen many Keycloak-Spring Boot tutorials where the `ROLE_` prefix was explicitly set which was redundant as the `SimpleAuthorityMapper` defaults to the correct prefix.

Since Spring's documentation for this mapper is very clear, I suspect that unnecessary configuration may come from a misunderstanding of the _"Use (…) `SimpleAuthorityMapper` to insert the `ROLE_` prefix"_. I think the code example I suggest can reduce superfluous configuration in many projects that rely on this mapper.

Furthermore, the example shows how to convert role names to upper case.

2021-12-22 18:47 UTC, andymunro commented on securing_apps/topics/oidc/java/spring-security-adapter.adoc
> +Use, for example, `org.springframework.security.core.authority.mapping.SimpleAuthorityMapper` which allows for case conversion and the addition of a prefix (which defaults to `ROLE_`).
@little-pinecone Add a comma before the first which.

2021-12-22 18:47 UTC, andymunro requested changes
Thanks, @little-pinecone.  Just one change requested.

2021-12-23 19:04 UTC, andymunro commented
To resolve the Expected message, use this command:  git pull upstream main

2023-03-13 12:58 UTC, ahus1 commented
@little-pinecone - thanks for sharing this documentation update as a pull request and sorry for us taking so long to review it. 

To you happens to have an example project at hand which implements it this way so I can try out this or a similar example?

2023-03-14 05:23 UTC, little-pinecone commented
@ahus1 The example project can be found here: https://github.com/little-pinecone/keycloak-spring-boot/blob/master/src/main/java/in/keepgrowing/keycloakspringboot/security/config/SecurityConfig.java

2023-04-04 16:03 UTC, ahus1 commented
The contents of this PR have been moved to the main repository as the documentation has been moved there: https://github.com/keycloak/keycloak/pull/19536

2023-04-04 16:03 UTC, closed without merging