Switch default offline sessions to lazy loaded
keycloak/keycloak-documentation pull request #1362
Opened 2022-01-17 13:33 UTC by martin-kanis

2022-01-18 22:36 UTC, andymunro submitted a review, later dismissed

2022-01-28 15:09 UTC, andymunro commented on release_notes/topics/17_0_0.adoc
> +To change the default behavior, see link:{adminguide_link}#_offline-sessios-preloading[{adminguide_name}].
#offline-sessions-preloading  No underscore and include the N in sessions

2022-01-28 15:09 UTC, andymunro commented on server_admin/topics/sessions/preloading.adoc
> +[[_offline-sessios-preloading]]
offline-sessions-preloading

2022-01-28 15:11 UTC, andymunro commented on server_admin/topics/sessions/preloading.adoc
> +It can be achieved by setting `preloadOfflineSessionsFromDatabase` property in `userSessions` SPI to `true`.
Add "the" before `userSessions`

2022-01-28 15:11 UTC, andymunro requested changes
Thanks, @martin-kanis.  Just a few comments.

2022-01-28 15:22 UTC, martin-kanis commented
Thanks @andymunro. Done.

2022-01-28 17:04 UTC, andymunro approved these changes
Thanks, @martin-kanis.  Looks good.

2022-02-03 20:44 UTC, hmlnarik approved these changes

2022-02-03 20:44 UTC, merged