Add page about well-known endpoint configuration
keycloak/keycloak-documentation pull request #1379
Opened 2022-01-26 02:24 UTC by bouchardmathieu-qc

Keycloak has a way to specify an override file to modify the content of the well-known endpoint configuration. But it is not documented.

This PR add a new section about this topic and an example configuration to modify the advertised response types.

2022-01-26 18:24 UTC, andymunro commented on server_admin/topics/sso-protocols/con-server-oidc-wellknown.adoc
> +WARNING:  The override file will only modify the `well-known` endpoint configuration. All the options will still be available in the admin console. The override file is also global and will modify th
We now standardizing on "Admin Console"

2022-01-26 18:25 UTC, andymunro requested changes
Just one change needed. Thanks.

2022-01-27 01:14 UTC, bouchardmathieu-qc commented on server_admin/topics/sso-protocols/con-server-oidc-wellknown.adoc
> +WARNING:  The override file will only modify the `well-known` endpoint configuration. All the options will still be available in the admin console. The override file is also global and will modify th
Corrected in the updated pull request

2022-01-27 01:14 UTC, bouchardmathieu-qc commented
I updated the pull request with the requested modification.

2022-01-27 15:40 UTC, andymunro approved these changes

2023-03-13 11:34 UTC, ahus1 commented
@bouchardmathieu-qc - thanks for contributing this documentation, and sorry it took so long to review this PR.

The SPI you're documenting here is located in `keycloak-services`. 

Only those SPIs that are located in `keycloak-server-spi` are considered public SPIs which are consider stable and safe for extension. All other SPIs can be used, but can change (or even vanish) in a future version, and are not supported. Therefore we tend to not document them. You can still use them, with the risk explained before. 

Therefore I'm closing this PR.

2023-03-13 11:34 UTC, closed without merging