Expected Scopes of ClientScopesCondition created on Admin UI are not …
keycloak/keycloak-documentation pull request #1394
Opened 2022-02-02 00:06 UTC by tnorimat

…saved onto ClientScopesCondition.Configuration

Closes #9371

2022-02-02 00:08 UTC, tnorimat commented
This PR is for https://github.com/keycloak/keycloak/pull/9526

2022-02-03 07:59 UTC, mposolda submitted a review, later dismissed
@tnorimat Thanks!

@andymunro Do you please have a chance to review?

2022-02-03 12:43 UTC, andymunro commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +If you used a policy including client-scopes condition and edited JSON document directly, you will need to change "scope" field name in a JSON document to "scopes".
Please add "the" after "change"

2022-02-03 12:44 UTC, andymunro requested changes
Thanks, @tnorimat.  Just one small change.

2022-02-03 23:13 UTC, tnorimat commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +If you used a policy including client-scopes condition and edited JSON document directly, you will need to change "scope" field name in a JSON document to "scopes".
Yes, I've fixed it as you've suggested.

2022-02-03 23:13 UTC, tnorimat commented
@andymunro Thank you.  I've fixed it as you've suggested.

2022-02-04 16:26 UTC, andymunro approved these changes
Thanks, @tnorimat Looks good.

2022-02-04 17:01 UTC, mposolda commented
@andymunro Thanks for the review!

2022-02-04 17:01 UTC, mposolda approved these changes

2022-02-04 17:01 UTC, merged