Add section about the Liquibase upgrade in the release notes
keycloak/keycloak-documentation pull request #1404
Opened 2022-02-09 16:45 UTC by sguilhen

2022-02-09 18:32 UTC, hmlnarik commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +to have CockroachDB as one of the supported databases for the new storage.
```suggestion
Liquibase was updated from version 3.5.5 to 4.6.2, which includes, among other things, several bug fixes, and a new way of registering custom extensions
via ServiceLoader.
```

2022-02-09 18:41 UTC, hmlnarik commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +that users run into unexpected issues when upgrading.
Suggestion:
```suggestion
but we would like to stress the importance of closely following Upgrading guide, specifically of *backing up existing database before upgrade*. While we did our best
to test the consequences of the Liquibase upgrade, some installations could be using specific setup unknown to us.
```

2022-02-09 19:29 UTC, sguilhen commented
@andymunro Can you please review these changes?

2022-02-09 19:54 UTC, andymunro commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +via `ServiceLoader`.
Change "via" (which is Latin) to "using" (which is English).

2022-02-09 19:54 UTC, andymunro commented on upgrading/topics/keycloak/changes-17_0_0.adoc
> +Migration from previous Keycloak versions to Keycloak 17.0.0 has been extensively tested with all the currently supported databases,
Remove "the" after "all"

2022-02-09 19:56 UTC, andymunro requested changes
Thanks, @sguilhen. Just a couple of minor changes.

2022-02-09 20:15 UTC, sguilhen commented
@andymunro Thank you for the review. Just pushed a new version incorporating your suggestions.

2022-02-09 20:18 UTC, andymunro approved these changes
Thanks, @sguilhen

2022-02-10 09:09 UTC, hmlnarik approved these changes
Thanks for the PR!

2022-02-10 09:09 UTC, merged