Add documentation for recovery codes preview feature.
keycloak/keycloak-documentation pull request #1429
Opened 2022-03-08 15:03 UTC by stelewis-redhat

See code PR at https://github.com/keycloak/keycloak/pull/8730.

2022-03-09 13:31 UTC, mposolda submitted a review, later dismissed
@stelewis-redhat Thanks!

@andymunro Do you please also have a chance to review this PR?

2022-03-09 21:52 UTC, andymunro commented on server_admin/topics/authentication/recovery-codes.adoc
> +You can configure Recovery codes as two-factor authenticator. You need to add authenticator 'Recovery Authentication Code Form' as two-factor authenticator to your authentication flow. See the WebAut
Would this more concise version communicate the same information?

You can configure Recovery codes for two-factor authentication by adding 'Recovery Authentication Code Form' as a two-factor authenticator to your authentication flow. For an example of configuring this authenticator, see the WebAuthn section in xref:configuring-authentication[Configuring authentication].

2022-03-09 21:53 UTC, andymunro requested changes
@stelewis-redhat One change suggested.

2022-03-09 22:16 UTC, stelewis-redhat commented
> 

Done!

2022-03-09 22:17 UTC, andymunro approved these changes
Thanks for the quick fix. thanks, @stelewis-redhat

2022-03-09 22:18 UTC, stelewis-redhat commented
> Thanks for the quick fix. thanks, @stelewis-redhat

No problem. Who typically merges, after approval? Is that something I need to do?

2022-03-09 22:31 UTC, andymunro commented
@stelewis-redhat Actually, I documented the complete process for updating the documentation including approvers.  Yes you need QE and engineering approval before it is merged.  Also, we need to update the RH SSO version after the Keycloak version is merged. Full details are here:  
https://docs.google.com/document/d/1JWiPkLVpyA9TebomUN9wmMM1l1mXO0GhgAkcBLK0xBI/edit#heading=h.k98lwg41g67j

@mposolda, @stianst  The last file changed above is for the Installation Guide. However, starting at Keycloak 17, we have a new installation guide.  https://www.keycloak.org/guides#server Does that guide need to be updated?

2022-03-10 03:28 UTC, stelewis-redhat commented
> @stelewis-redhat Actually, I documented the complete process for updating the documentation including approvers. Yes you need QE and engineering approval before it is merged. Also, we need to update the RH SSO version after the Keycloak version is merged. Full details are here: https://docs.google.com/document/d/1JWiPkLVpyA9TebomUN9wmMM1l1mXO0GhgAkcBLK0xBI/edit#heading=h.k98lwg41g67j
> 
> @mposolda, @stianst The last file changed above is for the Installation Guide. However, starting at Keycloak 17, we have a new installation guide. https://www.keycloak.org/guides#server Does that guide need to be updated?

Thanks, @andymunro. Is there a list of people who are QE and engineering? Or is it a group name I can tag?

2022-03-10 12:11 UTC, mposolda approved these changes

2022-03-10 12:15 UTC, mposolda commented
@andymunro Thanks for the review! Good point regarding new guide. I see that this page would also require update https://www.keycloak.org/server/features . However this page is not anymore in the "keycloak/keycloak-documentation" repository, but in the main repository "keycloak/keycloak" inside this file https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/features.adoc . So this PR for "keycloak-documentation" is fine, but the PR for the main codebase will need one small update to that file to reflect the docs.

@stelewis-redhat This PR is fine after Andrew and myself reviewed it. I am approving and I am planning to merge once also codebase PR is going to be merged. Can I request one more small update for the "features.adoc" file in the main repository?

2022-03-10 14:03 UTC, stelewis-redhat commented
> @andymunro Thanks for the review! Good point regarding new guide. I see that this page, which is part of new installation guide, will require update https://www.keycloak.org/server/features . However this page is not anymore in the "keycloak/keycloak-documentation" repository, but in the main repository "keycloak/keycloak" inside this file https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/features.adoc . So this PR for "keycloak-documentation" is fine, but the PR for the main codebase will need one small update to that file to reflect the docs.
> 
> @stelewis-redhat This PR is fine after Andrew and myself reviewed it. I am approving and I am planning to merge once also codebase PR is going to be merged. Can I request one more small update for the "features.adoc" file in the main repository? I really hope this is the last piece to have this stuff merged! Thanks for all your work on this!

OK, I'm looking at features.adoc and I don't see where ctx.features.preview is coming from. Gotta figure that out and then I'll push.

EDIT: @mposolda it looks like that features.adoc is driven from Profile.java, so there's no more changes to make?

2022-03-10 14:50 UTC, merged

2022-03-10 14:59 UTC, andymunro commented
@stelewis-redhat Let me know if you have an issues updating the RH SSO documentation with the same change using these instructions:   https://docs.google.com/document/d/1JWiPkLVpyA9TebomUN9wmMM1l1mXO0GhgAkcBLK0xBI/edit#heading=h.k98lwg41g67

2022-03-10 15:09 UTC, stelewis-redhat commented
> @stelewis-redhat Let me know if you have an issues updating the RH SSO documentation with the same change using these instructions: https://docs.google.com/document/d/1JWiPkLVpyA9TebomUN9wmMM1l1mXO0GhgAkcBLK0xBI/edit#heading=h.k98lwg41g67

@andymunro when it says "Begin the description with a link to the GitHub Issue." which GitHub issue should I use? I didn't create an issue for this project, just the PR.

2022-03-10 15:21 UTC, stelewis-redhat commented
@andymunro is there a way to add a label to an issue after the fact? I don't seem to be able to edit the labels in https://github.com/keycloak/keycloak-documentation/issues/1433.