Adding reference of nodejs adapter usage from keycloak quickstart example
keycloak/keycloak-documentation pull request #1430
Opened 2022-03-09 14:30 UTC by pacostas

2022-03-09 21:46 UTC, mhdawson commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +Another example of Node.js adapter usage can be found on https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloack quickstarts for nodejs]
```suggestion
==== Complete example 

A complete example using the Node.js adapter usage can be found in https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloack quickstarts for nodejs]
```

2022-03-09 21:47 UTC, mhdawson commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +Another example of Node.js adapter usage can be found on https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloack quickstarts for nodejs]
@pacostas just a few suggestions in terms of wording but this looks like a good place to include a reference.

2022-03-23 13:02 UTC, abstractj commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +A complete example using the Node.js adapter usage can be found in https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloack quickstarts for nodejs]
We have a typo here. keycloack vs Keycloak.

Please replace by Keycloak quickstarts for NodeJS

2022-03-23 13:02 UTC, abstractj requested changes
Please see my comments.

2022-03-23 13:18 UTC, abstractj commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +A complete example using the Node.js adapter usage can be found in https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloak quickstarts for nodejs]
Please replace Nodejs by Node.js

2022-03-23 13:50 UTC, abstractj submitted a review, later dismissed
Changes look good to me and before merging it I can squash all the commits in a single one.

2022-03-23 15:22 UTC, mhdawson commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +A complete example using the Node.js adapter usage can be found in https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[keycloak quickstarts for Node.js]
```suggestion
A complete example using the Node.js adapter usage can be found in https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs/[Keycloak quickstarts for Node.js]
```

2022-03-29 14:33 UTC, mhdawson commented
@abstractj I think all your updated requests where addressed.  I think the external links failures are not related to this PR.

2022-03-29 15:43 UTC, abstractj approved these changes

2022-03-29 15:43 UTC, abstractj commented
@mhdawson thank you for all the submissions!

2022-03-29 15:44 UTC, merged