Converting all variable type definitions from var to const or let
keycloak/keycloak-documentation pull request #1435
Opened 2022-03-13 11:47 UTC by pacostas

Replacing var type definitions in documentation to const or let.

2022-03-23 12:58 UTC, abstractj approved these changes, later dismissed

2022-03-23 12:58 UTC, abstractj commented
@jonkoops LGTM, but I will wait for your approval before merge.

2022-03-23 17:10 UTC, jonkoops requested changes

2022-03-23 17:10 UTC, jonkoops commented on aggregation/navbar.html
> +    let newtoc = document.createElement('div');
Why is `newtoc` defined with `let`? As far as I can see this variable is never re-assigned so should be fined to make it a constant.
```suggestion
    const newtoc = document.createElement('div');
```

2022-03-23 17:10 UTC, jonkoops commented on authorization_services/topics/enforcer-js-adapter.adoc
> +let authorizationRequest = {};
Same here, this is never re-assigned so can also be constant.
```suggestion
const authorizationRequest = {};
```

2022-03-23 17:10 UTC, jonkoops commented on authorization_services/topics/policy-js-policy.adoc
> +let permission = $evaluation.getPermission();
```suggestion
const permission = $evaluation.getPermission();
```

2022-03-23 17:10 UTC, jonkoops commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +    let req = new XMLHttpRequest();
```suggestion
    const req = new XMLHttpRequest();
```

2022-03-24 14:21 UTC, jonkoops commented
Looks like we have some failing tests. Can we get a rebase?

2022-03-24 17:15 UTC, pacostas commented
Sure, just rebased it

2022-03-25 15:00 UTC, jonkoops approved these changes

2022-03-25 15:07 UTC, jonkoops commented
The problems with external links are unrelated to the changes here. @abstractj could you go ahead and merge this PR?

2022-03-25 15:07 UTC, abstractj approved these changes

2022-03-25 15:08 UTC, merged

2022-03-25 15:08 UTC, jonkoops commented
@pacostas Thanks for your contribution :100: