Document `scope` option in keycloakjs.init
keycloak/keycloak-documentation pull request #1447
Opened 2022-03-28 13:40 UTC by tobilarscheid

According to https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/keycloak.js#L151-L153 the scope is read during parsing of the init options. This information was missing from the documentation.

2023-03-13 11:14 UTC, ahus1 submitted a review, later dismissed
Thank you for this documentation update!

2023-03-13 13:02 UTC, andymunro commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +to {project_name} will contain the scope parameter `scope=openid address phone`.
```suggestion
* scope - Used to forward the scope parameter to the {project_name} login endpoint. Use a space-delimited list of scopes. Those typically
reference link:{adminguide_link}#_client_scopes[Client scopes] defined on a particular client. Note that the scope `openid` is
always added to the list of scopes by the adapter. For example, if you enter the scope options `address phone`, then the request
to {project_name} will contain the scope parameter `scope=openid address phone`.
```

2023-03-13 13:03 UTC, andymunro commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +* scope - Override the scope configured in `init` with a different value for this specific login
```suggestion
* scope - Override the scope configured in `init` with a different value for this specific login.
```

2023-03-13 13:04 UTC, andymunro requested changes
Looks good. Approved if these minor changes are made.

2023-03-13 14:10 UTC, andymunro approved these changes

2023-03-14 13:49 UTC, ahus1 approved these changes

2023-03-17 09:04 UTC, mhajas approved these changes
Approving per @ahus1 's and @andymunro 's approvals

2023-03-17 09:04 UTC, merged