Update migration documentation for node.js adapter about logout
keycloak/keycloak-documentation pull request #1454
Opened 2022-03-31 07:24 UTC by mposolda

Closes #1453

2022-03-31 07:25 UTC, mposolda commented
@jonkoops @andymunro Do you please have a chance to review this?

2022-03-31 08:38 UTC, jonkoops requested changes

2022-03-31 08:38 UTC, jonkoops commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +- For the node.js adapter, same applies as for the javascript adapter. You are encouraged to update to the latest version as the older version of the adapter uses the deprecated `redirect_uri` parame
```suggestion
- For the Node.js adapter, same applies as for the JavaScript adapter. You are encouraged to update to the latest version as the older version of the adapter uses the deprecated `redirect_uri` parameter.
```

2022-03-31 08:38 UTC, jonkoops commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  With the latest node.js adapter, you are not affected as long as you use the logout based on the `/logout` URL as described in the documentation or in the node.js adapter example. However in the ca
```suggestion
  With the latest Node.js adapter, you are not affected as long as you use the logout based on the `/logout` URL as described in the documentation or in the Node.js adapter example. However in the case
```

2022-03-31 08:55 UTC, mposolda commented
@jonkoops Applied your suggestions. Thanks!

2022-03-31 08:56 UTC, jonkoops submitted a review, later dismissed
LGTM

2022-03-31 12:53 UTC, andymunro commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +- For the Node.js adapter, same applies as for the JavaScript adapter. You are encouraged to update to the latest version as the older version of the adapter uses the deprecated `redirect_uri` parame
the same guideline

2022-03-31 12:53 UTC, andymunro commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  With the latest Node.js adapter, you are not affected as long as you use the logout based on the `/logout` URL as described in the documentation or in the Node.js adapter example. However in the ca
Add a comma after However,

2022-03-31 12:54 UTC, andymunro commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  when your application directly uses method `keycloak.logoutUrl`, you can consider adding `idTokenHint` as the second argument to this method. The possibility to add `idTokenHint` as second argument
add "the" before "method"

2022-03-31 13:06 UTC, andymunro commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  added in this version. The `idTokenHint` needs to be valid ID Token, which was obtained during the login. Adding `idTokenHint` is optional and  If you don't add it, your users will need to confirm
needs to be a valid ID Token that was obtained during the login

Use that (without a preceding comma) when the following phrase qualifies the earlier phrase --- it is the specifically the token that was obtained during the login.
Use ", which" to begin a phrase that does not qualify the earlier phrase.

2022-03-31 13:10 UTC, andymunro commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  screen as described above. Also they won't be redirected back to the application after logout.
change " optional and  If you don't add it, your users will need to confirm logout   screen as described above. Also they won't be redirected back to the application after logout."
TO
"optional, but if you omit it, your users will need to confirm the logout screen as described earlier. Also they will not be redirected back to the application after logout."

2022-03-31 13:11 UTC, andymunro requested changes
Looks good, @mposolda. A few suggested changes.

2022-03-31 13:33 UTC, mposolda commented on upgrading/topics/keycloak/changes-18_0_0.adoc
> +  added in this version. The `idTokenHint` needs to be valid ID Token, which was obtained during the login. Adding `idTokenHint` is optional and  If you don't add it, your users will need to confirm
Thanks for the hint!

2022-03-31 13:38 UTC, mposolda commented
@andymunro I've applied all your suggestions. Thanks for the review!

2022-04-04 09:10 UTC, jonkoops approved these changes

2022-04-05 16:01 UTC, merged