Adding instructions on spinning up a Node.js server
keycloak/keycloak-documentation pull request #1457
Opened 2022-04-04 15:59 UTC by pacostas

Adding info on how to setup and start a Node.js server.

2022-05-09 19:52 UTC, abstractj commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +
I'd suggest removing the entire block above. Cover `git` steps is out of the scope for the Keycloak, plus Node.js developers are already familiar with `.gitignore`.

2022-05-10 12:43 UTC, pacostas commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +
Yeap!

2022-05-10 12:45 UTC, abstractj commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +    // Configure session
@pacostas I believe would make sense to indent the code below. Other than that, changes lgtm

2022-05-10 13:48 UTC, abstractj submitted a review, later dismissed
LGTM

2022-05-10 13:49 UTC, abstractj commented
@jonkoops waiting for your review, before merging it.

2022-05-12 08:56 UTC, jonkoops requested changes

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +In that case a Keycloak deployment is necessary to access keycloak admin console.
```suggestion
In that case a Keycloak deployment is necessary to access Keycloak admin console.
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +Please visit links on how to deploy a keycloak admin console with
```suggestion
Please visit links on how to deploy a Keycloak admin console with 
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +    })
```suggestion
    app.listen(3000, function () {
        console.log('App listening on port 3000');
    });
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +Last but not least, lets open a port and set our server, to listen for http requests on port 3000, by amending below code on server.js file.
```suggestion
Last but not least, let's set up our server to listen for HTTP requests on port 3000 by adding the following code to `main.js`:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +and set keycloak middleware as middleware in express, by pasting at the bottom of the file the below code
```suggestion
and configure Keycloak middleware in Express, by adding at the code below:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +At the root folder of your project create a file called server.js and add below block of code.
```suggestion
In the root directory of your project create a file called `server.js` and add the following code:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +Add `express-session` dependency:
```suggestion
Install the `express-session` dependency:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +    npm install express-session --save
```suggestion
    npm install express-session
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +To start the server.js script, add on package.json in scripts section, the start script:
```suggestion
To start the `server.js` script, add the following command in the 'scripts' section of the `package.json`:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +And now we have the ability to run our server with below command:
```suggestion
Now we have the ability to run our server with following command:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +        secret: "mySecret",
```suggestion
        secret: 'mySecret',
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +npm install express --save
```suggestion
    npm install express
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +In order to do so, first we have to install express in our dependencies
```suggestion
In order to do so, first we have to install Express:
```

2022-05-12 08:56 UTC, jonkoops commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +then require express in our project by pasting on top of the server.js file the below code
```suggestion
then require Express in our project as outlined below:
```

2022-05-12 09:26 UTC, pacostas commented
@jonkoops Thank you for the Review! :)

2022-05-12 11:31 UTC, abstractj commented
@pacostas could you please squash your commits into a single one?

2022-05-12 12:03 UTC, pacostas commented
@abstractj Squashed

2022-05-12 12:08 UTC, abstractj approved these changes

2022-05-12 13:45 UTC, jonkoops approved these changes

2022-05-12 13:53 UTC, merged