[CIAM-2134] Documentation for session-limits-feature
keycloak/keycloak-documentation pull request #1467
Opened 2022-04-08 17:43 UTC by douglaspalmer

2022-04-12 12:19 UTC, mposolda requested changes
@douglaspalmer Thanks for the PR!

Is it possible to include also small note to the release notes - it is in the file 18_0_0.adoc. Please include "Thanks to" with the contributor, who sent original PR :-)

2022-04-13 16:22 UTC, mposolda submitted a review, later dismissed
@douglaspalmer Thanks!

2022-04-13 16:46 UTC, mposolda approved these changes, later dismissed

2022-04-13 16:47 UTC, mposolda commented
@andymunro Can you please review this?

2022-04-13 19:19 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +To add session limits to a flow perform the following steps.
Add a comma after flow (this in an introductory phrase)

2022-04-13 19:21 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +. Enter the required maximum number of sessions a user can have in this realm. If a value of 0 is used then this check is disabled.
should be 
If a value of 0 is used, this check is disabled.

" then" is not needed. Also, a comma should conclude an introductory phrase.

2022-04-13 19:21 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +. Enter the required maximum number of sessions a user can have for the client. If a value of 0 is used then this check is disabled.
If a value of 0 is used, this check is disabled.

2022-04-13 19:22 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +  Deny new session - when a new session is requested and the session limit is reached no new sessions can be created.
add a comma after reached
(introductory phrase)

2022-04-13 19:23 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +  Terminate oldest session - when a new session is requested and the session limit has been reached the oldest session will be removed and the new session created.
add a comma after reached

2022-04-13 19:24 UTC, andymunro requested changes
Looks good @mposolda. Just a few suggestions for changes.

2022-04-19 06:40 UTC, mposolda approved these changes
@douglaspalmer @andymunro Thanks for the review and fixes!

2022-04-19 06:41 UTC, merged