Document scope option for the init method
keycloak/keycloak-documentation pull request #1508
Opened 2022-04-27 09:26 UTC by epuronta

Keycloak.js supports specifying explicit scopes in `keycloak.init()`, but the option is missing from the documentation. This PR adds that documentation.

Adapter being documented:
https://github.com/keycloak/keycloak/blob/90fe97133c5b5474286b56121679393e46ff01df/adapters/oidc/js/src/keycloak.js#L152

2022-09-02 21:33 UTC, andymunro commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +reference link:{adminguide_link}#_client_scopes[Client scopes] defined on particular client. Note that the scope `openid` will be
```suggestion
reference link:{adminguide_link}#_client_scopes[Client scopes] defined on a particular client. Note that the scope `openid` will be
```

2022-09-02 21:33 UTC, andymunro requested changes
@epuronta One minor change to suggest. Thanks.

2022-09-09 07:57 UTC, epuronta commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +reference link:{adminguide_link}#_client_scopes[Client scopes] defined on particular client. Note that the scope `openid` will be
Thanks, fixed the missing article

2022-10-25 04:51 UTC, stianst commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +reference link:{adminguide_link}#_client_scopes[Client scopes] defined on a particular client. Note that the scope `openid` will be
```suggestion
reference link:{adminguide_link}#_client_scopes[Client scopes] defined on a particular client. Note that the scope `openid` will
```

2022-10-25 04:52 UTC, merged