update idp section with new admin ui
keycloak/keycloak-documentation pull request #1515
Opened 2022-05-05 16:25 UTC by edewit

fixes: #1489

2022-05-23 17:45 UTC, andymunro commented on server_admin/topics/identity-broker/default-provider.adoc
> +. Click *⚙️* (gear icon) of the *Identity Provider Redirector* row.
```suggestion
. Click the gear icon  *⚙️* on the *Identity Provider Redirector* row.
```

2022-05-23 17:54 UTC, andymunro commented on server_admin/topics/identity-broker/default-provider.adoc
> +. Set *Default Identity Provider* to the identity provider you want to redirect users to.
This step is already included below.

2022-05-23 20:24 UTC, andymunro commented on server_admin/topics/identity-broker/configuration.adoc
> +. Select card of the identity provider you want to add. {project_name} displays the configuration page for the identity provider you selected.
```suggestion
. Select the identity provider you want to add. {project_name} displays the configuration page for the identity provider you selected.
```

2022-05-23 21:04 UTC, andymunro requested changes
Thanks, looks good. Just a few changes @edewit.

2022-05-25 13:38 UTC, andymunro commented
Thanks, @edewit.  Another one ready to merge, @ssilvert 

Thanks also for replacing te GitHub screen shot with one for GitLab.

2022-05-25 14:11 UTC, andymunro approved these changes

2022-05-25 18:09 UTC, ssilvert approved these changes

2022-05-25 18:09 UTC, merged