updated screen shots to match the new ui
keycloak/keycloak-documentation pull request #1516
Opened 2022-05-06 10:05 UTC by edewit

fixes: #1490

2022-05-23 21:17 UTC, andymunro commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +image:{project_images}/fine-grain-client.png[Fine grain client]
Text on this screen is hard to read.  Can you shrink this screen by a quarter and recapture it?

2022-05-23 21:19 UTC, andymunro commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +image:{project_images}/fine-grain-client-permissions-tab-on.png[Fine grain permission tab]
Text on this screen is hard to read.  Can you shrink this screen by a quarter and recapture it?

2022-05-23 21:19 UTC, andymunro requested changes
Only two screen shot changes to suggest.

2022-05-25 00:31 UTC, andymunro commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +image:{project_images}/fine-grain-client-permissions-tab-on.png[Fine grain permission tab]
The others look good, but this one could still be resized.

2022-05-25 00:31 UTC, andymunro commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +image:{project_images}/fine-grain-view-leads-permissions.png[Fine grain view leads permissions]
This one could also benefit from being resized.

2022-05-25 00:33 UTC, andymunro commented on server_admin/topics/admin-console-permissions/fine-grain.adoc
> +image:{project_images}/fine-grain-client-permissions-tab-on.png[Fine grain client permissions]
This one could also be resized to be more legible.

2022-05-25 00:34 UTC, andymunro requested changes
@edewit A few more screens to resize to make the text legible. Otherwise, looks good.

2022-05-25 13:22 UTC, andymunro commented
Thanks, @edewit.  Looks good, but I still see two screens not showing up as being resized:

- fine-grain-client-permissions-tab-on.png
- fine-grain-users-permissions.png

2022-05-25 14:00 UTC, edewit commented
sorry, updated those now... @andymunro

2022-05-25 14:07 UTC, andymunro commented
Thanks for the quick update, @edewit.  Looks perfect.
Another PR ready to merge, @ssilvert

2022-05-25 14:07 UTC, andymunro approved these changes

2022-05-25 14:12 UTC, andymunro approved these changes

2022-05-25 18:25 UTC, ssilvert approved these changes

2022-05-25 18:25 UTC, merged