updated the "Assigning permissions..." to new ui
keycloak/keycloak-documentation pull request #1517
Opened 2022-05-09 08:50 UTC by edewit

fixes: #1487

2022-05-13 20:46 UTC, andymunro commented on server_admin/topics/roles-groups/con-role-scope-mappings.adoc
> +. Click *Scope* tab.
```suggestion
. Click the *Scope* tab.
```

2022-05-13 20:46 UTC, andymunro commented on server_admin/topics/roles-groups/con-role-scope-mappings.adoc
> +. Click *Client scopes* tab.
```suggestion
. Click the *Client scopes* tab.
```

2022-05-13 22:03 UTC, andymunro commented
@edewit Please change the chapter title to:  Assigning permissions using roles and groups 
So that it creates the correct anchor ID for when @agagancarczyk creates a PR to address the Learn More issue: https://github.com/keycloak/keycloak-admin-ui/issues/2571
More comments to come.

2022-05-16 20:18 UTC, andymunro commented on server_admin/topics/roles-groups/proc-creating-realm-roles.adoc
Step one in the procedure should be

ifeval::[{project_product}==true]
. Click *Add Role*.
endif::[]
ifeval::[{project_project}==true]
. Click *Create Role*.
endif::[]

2022-05-16 20:20 UTC, andymunro commented on server_admin/topics/roles-groups/proc-converting-composite-roles.adoc
> +. Click *Add associated roles*
```suggestion
. From the *Action* list, select *Add associated roles*.
```

2022-05-16 20:56 UTC, andymunro commented on server_admin/topics/roles-groups/proc-assigning-role-mappings.adoc
> +endif::[]
```suggestion
ifeval::[{project_product}==true]
. Click *Users* in the menu.
. Click the user that you want to perform a role mapping on. If the user is not displayed, click *View all users*.
. Click the *Role Mappings* tab.
. Click the role you want to assign to the user in the *Available Roles* box.
. Click *Add selected*.
endif::[]
ifeval::[{project_community}==true]
. Click *Users* in the menu.
. Click the user that you want to perform a role mapping on.
. Click the *Role mappings* tab.
. Click the *Assign role*.
. Select the role you want to assign to the user from the dialog.
. Click *Assign*.
endif::[]
```

2022-05-16 21:14 UTC, andymunro commented on server_admin/topics/roles-groups/proc-managing-groups.adoc
> +. Enter a group name in the *Create Group* dialog.
```suggestion
. Enter a group name.
```

2022-05-16 21:15 UTC, andymunro commented on server_admin/topics/roles-groups/proc-managing-groups.adoc
> +. Click *Create*.
Add one more step.
. Click the group name.

2022-05-16 21:18 UTC, andymunro commented on server_admin/topics/roles-groups/con-role-scope-mappings.adoc
> +You can view the role mappings in the *Scope* tab of each client.
```suggestion
You can view the role mappings for a client.

.Procedure
```

2022-05-16 21:33 UTC, andymunro commented on server_admin/topics/roles-groups/con-role-scope-mappings.adoc
> +. Click *<client-name>-dedicated* scope.
I think this is supposed to be:
. Click the link under *Assigned client scope*.
 OR the link in the row with
*Dedicated scope and mappers for this client*

2022-05-17 15:54 UTC, andymunro commented on server_admin/topics/roles-groups/proc-managing-groups.adoc
> +. Click *Leave* button on the group table row.
```suggestion
. Click *Users* in the menu.
. Click the user to be removed from the group.
. Click *Leave* on the group table row.
```

2022-05-17 15:57 UTC, andymunro commented on server_admin/topics/roles-groups/proc-specifying-default-groups.adoc
>  .Default groups
Can you recapture this screen after making it smaller.  The text is hard to read.

2022-05-17 15:57 UTC, andymunro requested changes
Thanks, @edewit.  A few comments to address.

2022-05-18 13:30 UTC, andymunro commented on server_admin/topics/roles-groups/proc-using-default-roles.adoc
> +. Click *Realm settings* in the menu
```suggestion
. Click *Realm settings* in the menu.
```

2022-05-18 13:31 UTC, andymunro commented on server_admin/topics/roles-groups/con-role-scope-mappings.adoc
> +. Click *Clients* in the menu
```suggestion
. Click *Clients* in the menu.
```

2022-05-25 13:33 UTC, andymunro commented
Thanks, @edewit.   Another one ready to merge, @ssilvert.

2022-05-25 14:10 UTC, andymunro approved these changes

2022-05-25 18:08 UTC, ssilvert approved these changes

2022-05-25 18:08 UTC, merged