updated to reflect the new admin ui
keycloak/keycloak-documentation pull request #1518
Opened 2022-05-09 09:59 UTC by edewit

fixes: #1484

2022-05-17 16:32 UTC, andymunro commented on server_admin/topics/users/proc-allow-user-to-delete-account.adoc
> +. Select *delete-account*.
```suggestion
. Click *account delete-account*.
```

2022-05-17 18:22 UTC, andymunro commented on server_admin/topics/users/proc-configuring-user-attributes.adoc
> +endif::[]
```suggestion
ifeval::[{project_product}==true]
. Click *Add an attribute*.
endif::[]
. Enter the attribute name in the *Key* field.
. Enter the attribute value in the *Value* field.
```

2022-05-17 19:56 UTC, andymunro requested changes
Looks good, @edewit. Just a few changes to suggest.

2022-05-25 13:28 UTC, andymunro commented
Thanks, @edewit. Another one  ready to merge, @ssilvert

2022-05-25 13:32 UTC, andymunro commented
Thanks, @edewit.   Another one ready to merge, @ssilvert.

2022-05-25 14:08 UTC, andymunro approved these changes

2022-05-25 18:07 UTC, ssilvert approved these changes

2022-05-25 18:07 UTC, merged