updated to match the new ui
keycloak/keycloak-documentation pull request #1528
Opened 2022-05-19 09:13 UTC by edewit

fixes: #1496

2022-05-26 13:41 UTC, andymunro commented on authorization_services/topics/hello-world-create-realm.adoc
>  . Toggle *User Enabled* to *ON*
```suggestion
. Toggle *User Enabled* to *ON*.
```

2022-05-26 13:44 UTC, andymunro commented on authorization_services/topics/hello-world-create-realm.adoc
>  image:{project_images}/getting-started/hello-world/create-user.png[alt="Add User"]
Can you slightly increase this screen shot so that "identity providers" in the menu is not cut off?

2022-05-26 13:46 UTC, andymunro commented on authorization_services/topics/hello-world-create-realm.adoc
>  . Complete the *New Password* and *Password Confirmation* fields with a password and click the *Temporary* switch to *OFF*.
```suggestion
. Complete the *New Password* and *Password Confirmation* fields and toggle *Temporary* to *OFF*.
```

2022-05-26 13:48 UTC, andymunro commented on authorization_services/topics/hello-world-create-resource-server.adoc
>  . Click *Clients* to start creating a client application.
```suggestion
. Click *Clients* in the menu.
```

2022-05-26 13:48 UTC, andymunro commented on authorization_services/topics/hello-world-create-resource-server.adoc
> +. Toggle *Authorization* to ON.
```suggestion
. Toggle *Client authentication* to *ON*.
. Toggle *Authorization* to *ON*.
```

2022-05-26 13:52 UTC, andymunro commented on authorization_services/topics/hello-world-create-resource-server.adoc
> +. Fill in the *Client ID* and *Client Protocol*.
```suggestion
. Fill in the *Client type*.
```

2022-05-26 13:57 UTC, andymunro commented on authorization_services/topics/hello-world-create-resource-server.adoc
> +. Fill in the *Root URL* field.
```suggestion
. Scroll down to the *Capability config* section.
. Fill in the *Root URL* field.
```

2022-05-26 14:10 UTC, andymunro commented on authorization_services/topics/hello-world-create-resource-server.adoc
> +ifeval::[{project_product}==true]
```suggestion
+
The Client Settings page is displayed.
```

2022-05-26 14:30 UTC, andymunro commented on authorization_services/topics/hello-world-deploy.adoc
> +. Select *Download adapter config* from the drop-down list.
```suggestion
. From the *Action* list, select *Download adapter config*.
```

2022-05-26 14:31 UTC, andymunro commented on authorization_services/topics/hello-world-deploy.adoc
>  . From the Format Option item list, select *Keycloak OIDC JSON*.
```suggestion
. From the Format Option list, select *Keycloak OIDC JSON*.
```

2022-05-26 14:36 UTC, andymunro requested changes
Looks good, @edewit.  Just a few changes to suggest.

2022-05-31 12:21 UTC, andymunro approved these changes
Thanks, @edewit. Ready to merge, @ssilvert

2022-06-01 11:42 UTC, ssilvert approved these changes

2022-06-01 11:42 UTC, merged