Updated to the new UI
keycloak/keycloak-documentation pull request #1529
Opened 2022-05-19 09:43 UTC by edewit

fixes: #1497

2022-05-26 14:54 UTC, andymunro commented on authorization_services/topics/resource-server-create-client.adoc
> +. Click *Save*.
```suggestion
. Click *Save*.
. Scroll down to the *Capability config* section.
```

2022-05-26 14:55 UTC, andymunro commented on authorization_services/topics/resource-server-enable-authorization.adoc
> +To turn your OIDC Client Application into a resource server and enable fine-grained authorization, click the *Authorization Enabled* switch to *ON* then click *Save*.
```suggestion
To turn your OIDC Client Application into a resource server and enable fine-grained authorization, toggle *Authorization Enabled* to *ON* and click *Save*.
```

2022-05-26 14:59 UTC, andymunro commented on authorization_services/topics/resource-server-enable-authorization.adoc
>  To turn your OIDC Client Application into a resource server and enable fine-grained authorization, select *Access type* *confidential* and click the *Authorization Enabled* switch to *ON* then click
```suggestion
To turn your OIDC Client Application into a resource server and enable fine-grained authorization, select *Access type* *confidential* and toggle *Authorization Enabled* to *ON* then click *Save*.
```

2022-05-26 15:39 UTC, andymunro commented on authorization_services/topics/resource-server-create-client.adoc
> +. Click *Save*.
Line 39 should be:
ifeval::[{project_product}==true]
. Click *Save*. 
+
The client is created and the client Settings page opens. A page similar to the following is displayed:
endif::[]
ifeval::[{project_community}==true]
. Click *Save*. 
+
The client is created.
endif::[]

2022-05-26 15:49 UTC, andymunro commented on authorization_services/topics/resource-server-enable-authorization.adoc
```suggestion
+
```

2022-05-26 19:34 UTC, andymunro commented on authorization_services/topics/resource-server-import-config.adoc
>  . Navigate to the *Resource Server Settings* page.
```suggestion
. Click *Clients* in the menu.
* Click the client you created as a resource server.
```

2022-05-26 19:39 UTC, andymunro commented on authorization_services/topics/resource-server-import-config.adoc
>  . Click the *Export Settings* tab.
```suggestion
. Click *Clients* in the menu.
* Click the client you created as a resource server.
```
```

2022-05-26 19:39 UTC, andymunro commented on authorization_services/topics/resource-server-import-config.adoc
>  image:{project_images}/resource-server/authz-export.png[alt="Export Settings"]
```suggestion
image:{project_images}/resource-server/authz-export.png[Export Settings]
```

2022-05-26 19:40 UTC, andymunro commented on authorization_services/topics/resource-server-import-config.adoc
>  image:{project_images}/resource-server/authz-settings.png[alt="Import Settings"]
```suggestion
image:{project_images}/resource-server/authz-settings.png[Import Settings]
```

2022-05-26 19:40 UTC, andymunro commented on authorization_services/topics/resource-server-enable-authorization.adoc
>  image:{project_images}/resource-server/client-enable-authz.png[alt="Enabling authorization services"]
```suggestion
image:{project_images}/resource-server/client-enable-authz.png[Enabling authorization services]
```

2022-05-26 19:41 UTC, andymunro commented on authorization_services/topics/resource-server-create-client.adoc
>  image:{project_images}/resource-server/client-list.png[alt="Clients"]
```suggestion
image:{project_images}/resource-server/client-list.png[Clients]
```

2022-05-26 19:41 UTC, andymunro commented on authorization_services/topics/resource-server-create-client.adoc
>  image:{project_images}/resource-server/client-create.png[alt="Add Client"]
```suggestion
image:{project_images}/resource-server/client-create.png[Add Client]
```

2022-05-26 20:31 UTC, andymunro requested changes
Looks good, @edewit. Just a few changes.

2022-05-31 12:29 UTC, andymunro approved these changes

2022-05-31 12:32 UTC, andymunro commented
@edewit looks good. Ready to merge, @ssilvert

2022-06-01 18:10 UTC, ssilvert approved these changes

2022-06-01 18:10 UTC, merged