updated to reflect the new ui
keycloak/keycloak-documentation pull request #1531
Opened 2022-05-19 14:38 UTC by edewit

fixes: #1500

2022-05-27 21:24 UTC, andymunro commented on authorization_services/topics/permission-create-scope.adoc
"Apply Policy" on line 35 needs to be updated.   Now I see "Policy" instead.  I don't know if it is simply a name change.

2022-05-27 21:27 UTC, andymunro commented on authorization_services/topics/permission-create-resource.adoc
"Apply Policy" on line 40 needs to be updated. Now I see "Policy" instead. I don't know if it is simply a name change.

2022-05-27 21:34 UTC, andymunro requested changes
Thanks, @edewit.  Just two comments.

2022-05-31 12:15 UTC, andymunro approved these changes
Thanks, @edewit.  Ready to merge, @ssilvert

2022-06-01 11:43 UTC, ssilvert approved these changes

2022-06-01 11:43 UTC, merged

2022-06-01 12:35 UTC, edewit commented
@ssilvert merged into `main`? shouldn't it be merged to `new-admin-console`

2022-06-01 16:20 UTC, andymunro commented
yes, @edewit, @ssilvert should be merged to new-admin-console.  If it is not possible to back this out, we can figure out if this is actually a problem.

2022-06-01 18:14 UTC, ssilvert commented
@edewit @andymunro I didn't check to see that the PR was opened against main.

@edewit I have now reverted.  Can you open a new one against `new-admin-console`?