Update to reflect the new admin UI
keycloak/keycloak-documentation pull request #1532
Opened 2022-05-19 14:39 UTC by edewit

fixes: #1499

2022-06-06 19:04 UTC, andymunro commented on authorization_services/topics/policy-overview.adoc
> +. To create a new policy, click *Create policy* button, then select a policy type from the list.
```suggestion
. To create a new policy, click *Create policy*, then select a policy type from the list.
```

2022-06-06 21:03 UTC, andymunro commented on authorization_services/topics/policy-time-policy.adoc
> +* *Expire time *
```suggestion
* *Expire time*
```

2022-06-06 21:16 UTC, andymunro commented on authorization_services/topics/policy-time-policy.adoc
>  +
```suggestion

```

2022-06-06 21:21 UTC, andymunro commented on authorization_services/topics/policy-time-policy.adoc
>  +
Also, remove + (plus sign) on lines 48, 52, 56, and 64.

2022-06-06 21:30 UTC, andymunro commented on authorization_services/topics/policy-client-policy.adoc
>  image:images/policy/create-client.png[alt="Add a Client Policy"]
This is the old image.

2022-06-06 21:30 UTC, andymunro commented on authorization_services/topics/policy-client-policy.adoc
> +Specifies which clients are givenGroup-based policy access by this policy.
```suggestion
Specifies which clients have givenGroup-based policy access by this policy.
```

2022-06-06 22:00 UTC, andymunro commented on authorization_services/topics/policy-client-policy.adoc
>  image:images/policy/create-client.png[alt="Add a Client Policy"]
Also, there is an old image in policy-client-scope-policy-required-client-scope.adoc

2022-06-06 23:54 UTC, andymunro requested changes
A few corrections, @edewit

2022-06-08 20:39 UTC, andymunro commented on authorization_services/topics/policy-time-policy.adoc
>  * *Day of Month*
```suggestion

* *Day of Month*
```

2022-06-08 20:51 UTC, andymunro requested changes
Looking good @edewit. Just one minor change needed to fix a formatting problem.

2022-06-13 17:36 UTC, andymunro approved these changes
Okay to merge, @ssilvert 
Thanks, @edewit

2022-06-13 19:48 UTC, ssilvert approved these changes

2022-06-13 19:48 UTC, merged