Update cross-site instructions
keycloak/keycloak-documentation pull request #1565
Opened 2022-06-13 20:57 UTC by andymunro

Closes #1564

@tkyjovsk, @mposolda, @pskopek Can you verify this change?  We are no longer supporting RHDG 7.3.x for cross-site replication for RH SSO 7.6.

2022-06-29 16:49 UTC, andymunro commented
@iankko Can you approve this?

2022-06-29 17:09 UTC, tkyjovsk requested changes

2022-06-29 17:09 UTC, tkyjovsk commented on server_installation/topics/operating-mode/crossdc.adoc
> +**Automatically** - After some amount of failed backups, the `site2` will usually be taken offline automatically. This is done due the configuration of `take-offline` element inside the cache configu
amount --> number

2022-06-29 17:09 UTC, tkyjovsk commented on server_installation/topics/operating-mode/crossdc.adoc
> +* We recommended that you go through the procedure for xref:assembly-setting-up-crossdc[Setting up cross-site replication] and have this one working first, so that you have some understanding of how
recommended --> recommend

2022-06-29 17:49 UTC, iankko commented on server_installation/topics/operating-mode/crossdc.adoc
> +**Automatically** - After some amount of failed backups, the `site2` will usually be taken offline automatically. This is done due the configuration of `take-offline` element inside the cache configu
> amount --> number

@andymunro +1 on this. Per [Cambridge dictionary suggestion](https://dictionary.cambridge.org/grammar/british-grammar/amount-of-number-of-or-quantity-of) `amount of` is used for uncountable nouns, while `number of` for countable ones. Count of failed backups looks like a countable one.

Maybe replace with `After a certain number of failed backups....`?

2022-06-29 17:50 UTC, iankko reviewed
One small nitpick, but in general LGTM!
@andymunro Thanks, Andy!

2022-06-29 18:02 UTC, andymunro commented
The broken links are to 7.6 URLs that don't exist yet.

2022-06-29 20:05 UTC, andymunro commented
Thanks, @iankko, @tkyjovsk.  Please approve if it is okay now.

2022-06-30 12:02 UTC, tkyjovsk approved these changes

2022-06-30 12:57 UTC, tkyjovsk approved these changes

2022-06-30 12:57 UTC, iankko approved these changes
LGTM @andymunro Thanks, Andy!

2022-07-01 19:47 UTC, merged