Support JSON objects when evaluating claims in regex policy
keycloak/keycloak-documentation pull request #1566
Opened 2022-06-14 13:32 UTC by pedroigor

Closes #11514

2022-06-23 14:24 UTC, DGuhr approved these changes, later dismissed

2022-09-02 21:27 UTC, andymunro commented on authorization_services/topics/policy-regex-policy.adoc
> +object, the first path (e.g.: `contact`) should map to the attribute name holding the JSON object.
```suggestion
object, the first path (for example, `contact`) should map to the attribute name holding the JSON object.
```

2022-09-02 21:28 UTC, andymunro requested changes
One minor change, @pedroigor

2022-09-05 11:39 UTC, pedroigor commented
@andymunro Thanks.

2022-10-25 04:47 UTC, merged