Update Upgrading Guide for 7.6
keycloak/keycloak-documentation pull request #1592
Opened 2022-06-25 21:26 UTC by andymunro

Closes #1563

@vmuzikar and @pskopek Please review.

2022-06-27 07:29 UTC, vmuzikar requested changes
@andymunro Thanks for the PR!

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc
> +Previously, an unsupported metrics extension was added in the example for the creation of the Keycloak CR by the {project_operator}. This has been removed.
I wouldn't mention this. This mainly concerned the upstream, as in downstream we don't have the affected examples.

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc~
> +Previously, an unsupported metrics extension was added in the example for the creation of the Keycloak CR by the {project_operator}. This has been removed.
I wouldn't mention this. This mainly concerned the upstream, as in downstream we don't have the affected examples.

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc
> +This optional field will be ignored when the Operator is deployed on Kubernetes version 1.25 and higher.
From the RH-SSO perspective, there's nothing like "legacy operator".

```suggestion
With this release, we have deprecated `podDisruptionBudget` field in the Keycloak CR of {project_operator}.
This optional field will be ignored when the Operator is deployed on OCP 4.12 and newer.
```

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc~
> +link:{installguide_link}#_operator_production_usage[related chapter in the {installguide_name}].
I'm not sure how this got here. This was already affecting 7.5.1.

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc~
> +For more details, see the link:{installguide_link}#_proxy_env_vars[related chapter in the {installguide_name}].
This was [part of 7.5.1](https://issues.redhat.com/browse/KEYCLOAK-19420) but probably was missing from the  release notes. Not sure if we should mention it for 7.6.0.

2022-06-27 07:29 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc
> +For more details, see the link:{installguide_link}#_proxy_env_vars[related chapter in the {installguide_name}].
This was [part of 7.5.1](https://issues.redhat.com/browse/KEYCLOAK-19420) but probably was missing from the  release notes. Not sure if we should mention it for 7.6.0.

2022-06-27 15:40 UTC, andymunro commented
Thanks, @vmuzikar. Updates made.

2022-06-28 07:25 UTC, vmuzikar commented on upgrading/topics/rhsso/changes-76.adoc
> +This optional field will be ignored when the Operator is deployed on Kubernetes version 1.25 and higher.
```suggestion
This optional field will be ignored when the Operator is deployed on OCP 4.12 and newer.
```

2022-06-29 15:41 UTC, andymunro commented
@vmuzikar Can you approve this now?

2022-06-29 16:19 UTC, vmuzikar submitted a review, later dismissed
@andymunro Thanks for the update! As far as the Operator goes, LGTM. Can't comment on other changes. :)

2022-06-29 21:29 UTC, andymunro commented
Broken external links are to 7.6 URLs that are not yet created.

2022-06-30 14:27 UTC, miquelsi approved these changes, later dismissed

2022-06-30 15:08 UTC, miquelsi commented on topics/templates/document-attributes-product.adoc
> +:project_versionNpm: 18.0.2.redhat-00001
18.0.0

2022-06-30 15:54 UTC, andymunro commented
Okay thanks, @miquelsi. Please check and reapprove if okay.

2022-07-01 07:10 UTC, vmuzikar approved these changes

2022-07-01 07:55 UTC, miquelsi approved these changes

2022-07-01 13:34 UTC, abstractj approved these changes

2022-07-01 13:34 UTC, merged