Updated migration guide as more methods now throw exceptions.
keycloak/keycloak-documentation pull request #1598
Opened 2022-06-29 08:26 UTC by ahus1

Related to keycloak/keycloak#12556

2022-06-29 08:28 UTC, ahus1 commented
Hi @mhajas - as you've been involved in the original issue, ask you to review this documentation.
Please let me know if this works for you, or you'd want @hmlnarik to have a look instead.

2022-06-29 09:37 UTC, mhajas submitted a review, later dismissed
Thanks @ahus1. LGTM

2022-06-29 18:05 UTC, hmlnarik submitted a review, later dismissed

2022-07-01 14:08 UTC, andymunro commented on upgrading/topics/keycloak/changes-19_0_0.adoc
> +The same pattern of deprecation applies to methods of other object areas, e.g. `clients()` or `groups()`.
```suggestion
The same pattern of deprecation applies to methods of other object areas, such as `clients()` or `groups()`.
```

2022-07-01 14:09 UTC, andymunro commented on upgrading/topics/keycloak/changes-19_0_0.adoc
> +The next section describes how to migrate those calls to the new API, or use the legacy API while using the old store.
```suggestion
The next section describes how to migrate those calls to the new API or use the legacy API while using the old store.
```

2022-07-01 14:09 UTC, andymunro commented on upgrading/topics/keycloak/changes-19_0_0.adoc
> +All methods `++*StorageManager()++` and `++*LocalStorage++()` now throw an exception when being called, as there is no direct replacement in the new store.
Should it be "All methods of..." ?

2022-07-01 14:11 UTC, andymunro commented on upgrading/topics/keycloak/changes-19_0_0.adoc
> +The `keycloak-model-legacy-*` modules will be available for a longer time, and will eventually be removed.
```suggestion
The `keycloak-model-legacy-*` modules will be available for a longer time and will eventually be removed.
```

2022-07-01 14:12 UTC, andymunro requested changes
Looks good, @ahus1. Just a few suggestions.

As always, we avoid latin.  We use for example instead of e.g.

2022-07-01 15:00 UTC, ahus1 commented on upgrading/topics/keycloak/changes-19_0_0.adoc
> +All methods `++*StorageManager()++` and `++*LocalStorage++()` now throw an exception when being called, as there is no direct replacement in the new store.
I'll make this "All methods ending in ...", as the "*" is  a placeholder.

2022-07-01 15:20 UTC, andymunro requested changes
Looks good @ahus1

2022-07-01 15:20 UTC, andymunro approved these changes

2022-07-01 15:22 UTC, ahus1 commented
Thank you for that review - now I'll start looking for a maintainer. I also put one more Latin word to my auto-correction...

2022-07-01 17:12 UTC, merged