Add detail example for adding 'User Session Count Limit' execution to the browser authentication flow
keycloak/keycloak-documentation pull request #1619
Opened 2022-07-17 16:48 UTC by HwangTaehyun

Hi, Thank you for the amazing open source.

Recently, I added user session limit execution flow with my keycloak setting with the following reference.

* https://www.keycloak.org/docs/latest/server_admin/index.html#_step-up-flow:~:text=throw%20an%20error.-,User%20session%20limits,-Limits%20on%20the
* https://github.com/keycloak/keycloak/issues/10077

However, It isn't very clear for me to add this feature to the authorization flow.
It would be more helpful if there are more examples or additional explanations.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/42465090/179348946-1ab344fd-481c-4812-be57-127bfc1d66f9.png">

Thank you!

2022-09-02 21:14 UTC, andymunro commented on server_admin/topics/authentication/flows.adoc
> +Note that the user session limits execution should be added to your bound *Browser flow*, *Direct grant flow*, *Reset Credentials* and also to any *Post broker login flow*. If you want to add the use
```suggestion
Note that the user session limits execution should be added to your bound *Browser flow*, *Direct grant flow*, *Reset Credentials* and also to any *Post broker login flow*. To add the user session limits execution to *Browser Flow*, you should add this execution to *Forms Auth Type* by using the *Actions* button.
```

2022-09-02 21:15 UTC, andymunro requested changes
@HwangTaehyun One minor change to suggest.

2022-09-05 04:28 UTC, HwangTaehyun commented
@andymunro Thanks for the review! I've applied your suggestions. Also, I integrated the detailed explanation to add user session limits execution with #1662

2022-09-05 06:36 UTC, mposolda commented
@HwangTaehyun Thanks for the PR. I am closing it as the section of `User Session Limits` was updated in the meantime and it should be clearer how to configure "User Session Limits" . BTV. For the proper behaviour, it may be needed to add `User Session Limits` as the REQUIRED authenticator at the level 1 as described in the current docs and the example flow (The case you described when adding to the `Forms` flow won't work for some cases like for example authentication through Kerberos or X509)

2022-09-05 06:36 UTC, closed without merging