Release notes for dist changes
keycloak/keycloak-documentation pull request #1656
Opened 2022-08-10 11:57 UTC by pedroigor

2022-09-02 21:10 UTC, andymunro commented on release_notes/topics/20_0_0.adoc
> +In this release, we are introducing two additional server options to set a base URL for frontend and administration console URLs.
```suggestion
In this release, we are introducing two additional server options to set a base URL for front end and Admin Console URLs.
```

2022-09-02 21:11 UTC, andymunro commented on release_notes/topics/20_0_0.adoc
> +In this release, we are introducing two additional server options to set a base URL for frontend and administration console URLs.
We are now standardizing on Admin Console.

2022-09-02 21:11 UTC, andymunro requested changes
Thanks, @pedroigor One minor change.

2022-10-03 11:31 UTC, stianst approved these changes

2022-10-03 11:31 UTC, merged