Add H2 upgrade to release notes and migration guide
keycloak/keycloak-documentation pull request #1699
Opened 2022-10-14 16:42 UTC by ahus1

Relates to keycloak/keycloak#12607
Relates to keycloak/keycloak#11292
Relates to keycloak/keycloak#10113

2022-10-14 16:46 UTC, ahus1 commented
@hmlnarik - as you've been involved with the original PR #14819, I ask you to review this, or involve another developer.

@andymunro - could you please be so kind to review the contents that they comply with the style guide. 

Thanks!

2022-10-14 19:18 UTC, andymunro commented on release_notes/topics/20_0_0.adoc
> +In this release, we are making important changes to `kc.bat` in order to give the same experience as when running on Linux.
```suggestion
In this release, we are making important changes to `kc.bat` to give the same experience as when running on Linux.
```

2022-10-14 19:19 UTC, andymunro commented on upgrading/topics/keycloak/changes-20_0_0.adoc
> +This might require changes to the H2 JDBC URL or migration of the H2 database files in an existing Keycloak setup.
```suggestion
This change might require changes to the H2 JDBC URL or migration of the H2 database files in an existing Keycloak setup.
```

2022-10-14 19:23 UTC, andymunro commented on upgrading/topics/keycloak/changes-20_0_0.adoc
> +If an H2 JDBC URL is provided on the command line or a configuration file, and it already contains the `NON_KEYWORDS=` attribute in the JDBC URL, this attribute needs to be amended with the `VALUE` k
```suggestion
If an H2 JDBC URL is provided on the command line or in a configuration file, and it already contains the `NON_KEYWORDS=` attribute in the JDBC URL, this attribute needs to be amended with the `VALUE` keyword.
```

2022-10-14 19:26 UTC, andymunro requested changes
Looks good, @ahus1. Just a few suggestions.

2022-10-14 20:11 UTC, ahus1 commented
@andymunro - thanks for the review, I applied the changes. Will ask you for a re-review once I received a first feedback from @hmlnarik

2022-10-14 20:14 UTC, andymunro approved these changes

2022-10-17 06:58 UTC, hmlnarik approved these changes

2022-10-17 06:58 UTC, merged