Revise password blacklist documentation
keycloak/keycloak-documentation pull request #1742
Opened 2023-01-09 13:51 UTC by thomasdarimont

Depends on: https://github.com/keycloak/keycloak/pull/14411
See: https://github.com/keycloak/keycloak/issues/8982

2023-01-10 08:28 UTC, rmartinc submitted a review, later dismissed
Technical details are updated OK for issue https://github.com/keycloak/keycloak/issues/8982. Grammatical or style details are for somebody else... :smile:

2023-01-20 22:30 UTC, andymunro commented on server_admin/topics/authentication/password-policies.adoc
> +* The value must be the name of the blacklist file, e.g. `100k_passwords.txt`.
```suggestion
* The value must be the name of the blacklist file,  for example, `100k_passwords.txt`.
```

2023-01-20 22:31 UTC, andymunro commented on server_admin/topics/authentication/password-policies.adoc
> +** The `blacklistsPath` property of the `passwordBlacklist` policy SPI configuration. To configure the blacklist folder via CLI use `--spi-password-policy-password-blacklist-blacklists-path=/path/to/
```suggestion
** The `blacklistsPath` property of the `passwordBlacklist` policy SPI configuration. To configure the blacklist folder using the CLI, use `--spi-password-policy-password-blacklist-blacklists-path=/path/to/blacklistsFolder`.
```

2023-01-20 22:32 UTC, andymunro commented on server_admin/topics/authentication/password-policies.adoc
> +The current implementation uses a BloomFilter for fast and memory efficient containment checks, e.g. whether a given password is contained in a blacklist, with the possibility for false positives.
```suggestion
The current implementation uses a BloomFilter for fast and memory efficient containment checks, such as whether a given password is contained in a blacklist, with the possibility for false positives. 
```

2023-01-20 22:32 UTC, andymunro commented on server_admin/topics/authentication/password-policies.adoc
> +* To change the false positive probability via CLI configuration use `--spi-password-policy-password-blacklist-false-positive-probability=0.00001`
```suggestion
* To change the false positive probability by CLI configuration, use `--spi-password-policy-password-blacklist-false-positive-probability=0.00001`
```

2023-01-20 22:33 UTC, andymunro requested changes
A few suggested changes.

2023-01-23 12:20 UTC, thomasdarimont commented
@andymunro thanks for your review! I just applied your suggestions.

2023-01-23 12:46 UTC, thomasdarimont commented
I also fixed the three broken links (http -> https)  that caused this PR to fail.

2023-03-10 09:23 UTC, ahus1 commented
@thomasdarimont - thank you for providing this documentation update. 

Due to our long feedback cycle, this acquired some conflicts. Please rebase this PR. 

The one link to CSP has been fixed in the main branch already. 

The other change in the change log was also fixed, but differently from your suggestion: It was actually a key to be placed in the configuration file, not a link to be clicked, therefore it has been marked as pass-though content. 

Thanks!

2023-03-23 16:21 UTC, ahus1 commented
Superseded by https://github.com/keycloak/keycloak/pull/19280

2023-03-23 16:21 UTC, closed without merging