Restore internal to external token exchange documentation
keycloak/keycloak-documentation pull request #1747
Opened 2023-01-13 14:15 UTC by SRTigers98

Restored internal to external token exchange documentation from commit 0d9a22e643cc0b6db869fd7943625bbaefa5cf92 

Closes #1745

2023-01-20 22:29 UTC, andymunro submitted a review, later dismissed

2023-01-26 09:57 UTC, ahus1 requested changes
Thanks for restoring the parts that have been removed by error. 

Part of that change was also use `image` instead of `{project_images}`, so I ask you to apply this change to your pull request as well, as I assume images will otherwise not show in the built documentation.

When you've updated the docs, please ensure to squash the commits in this PR to a single commit. Thanks!

2023-01-26 09:57 UTC, ahus1 commented on securing_apps/topics/token-exchange/token-exchange.adoc
> +image:{project_images}/exchange-idp-client-policy.png[Client Policy Creation]
```suggestion
image:images/exchange-idp-client-policy.png[Client Policy Creation]
```

2023-01-26 09:57 UTC, ahus1 commented on securing_apps/topics/token-exchange/token-exchange.adoc
> +image:{project_images}/exchange-idp-apply-policy.png[Apply Client Policy]
```suggestion
image:images/exchange-idp-apply-policy.png[Apply Client Policy]
```

2023-01-27 13:32 UTC, ahus1 approved these changes
Thank you for restoring this content!

2023-01-30 12:39 UTC, ahus1 commented
To the maintainers merging this: The previous commit 0d9a22e643cc0b6db869fd7943625bbaefa5cf92 was supposed to remove content that was "product only" inside of `ifeval::[{project_product}==true])]` block. 

The content that's being restored here wasn't adjacent to such a product only block, but removed by accident, and is now being restored by this commit as it is still valid.

2023-02-22 17:07 UTC, stianst approved these changes

2023-02-22 17:11 UTC, merged