Add documentation for SAML SP metadata changes in KC 21
keycloak/keycloak-documentation pull request #1760
Opened 2023-01-31 09:14 UTC by mhajas

2023-01-31 14:00 UTC, andymunro commented on release_notes/topics/21_0_0.adoc
> +signing and encryption use. Starting with this version of Keycloak
```suggestion
Prior to this release, SAML SP metadata contained the same key for both
signing and encryption use. Starting with this version of Keycloak,
```

2023-01-31 14:00 UTC, andymunro commented on release_notes/topics/21_0_0.adoc
> +supported XML-Enc algorithms with the mapping to Keycloak realm keys.
```suggestion
the supported XML-Enc algorithms with the mapping to Keycloak realm keys.
```

2023-01-31 14:02 UTC, andymunro commented on server_admin/topics/identity-broker/saml.adoc
> +|Encryption algorithm, which is used by SAML IDP for encryption of SAML documents, assertions or IDs. The corresponding decryption key for decrypt SAML document parts will be chosen based on this con
```suggestion
|Encryption algorithm, which is used by SAML IDP for encryption of SAML documents, assertions, or IDs. The corresponding decryption key for decrypt SAML document parts will be chosen based on this configured algorithm and should be available in realm keys for the encryption (ENC) usage. If the algorithm is not configured, any supported algorithm is allowed and a decryption key will be chosen based on the algorithm specified in SAML document itself.
```

2023-01-31 14:03 UTC, andymunro commented on upgrading/topics/keycloak/changes-21_0_0.adoc
> +- either update IDP configuration with the metadata generated by a newer
```suggestion
- either update the IDP configuration with the metadata generated by a newer
```

2023-01-31 14:04 UTC, andymunro requested changes
Looks good. Just a few minor changes.

2023-01-31 14:15 UTC, mhajas commented
Thank you for the review @andymunro! I updated the PR based on your suggestions.

2023-01-31 15:30 UTC, andymunro approved these changes
Thanks, @mhajas.  Great job.

2023-02-07 08:41 UTC, mposolda approved these changes

2023-02-10 11:07 UTC, merged