SPNEGO Warning
keycloak/keycloak-documentation pull request #1770
Opened 2023-02-13 21:57 UTC by slominskir

Closes https://github.com/keycloak/keycloak/issues/16981

2023-02-14 14:39 UTC, slominskir commented
**Note**: If Keycloak adds a conditional SPNEGO authenticator in the future the doc provided here would be updated to reference the built-in authenticator instead of the issue ticket discussing the custom one used to work around the NTLM issue.

See: https://github.com/keycloak/keycloak/pull/17064

2023-02-22 11:10 UTC, mposolda submitted a review, later dismissed
@slominskir Thanks! This is useful note to add

@andymunro Can you please review as well?

2023-02-22 13:59 UTC, andymunro commented on server_admin/topics/authentication/kerberos.adoc
> +The https://www.ietf.org/rfc/rfc4559.txt[Negotiate] www-authenticate scheme allows NTLM as a fallback to Kerberos and on some web browsers in Windows NTLM is supported by default.  If a www-authentic
```suggestion
The https://www.ietf.org/rfc/rfc4559.txt[Negotiate] www-authenticate scheme allows NTLM as a fallback to Kerberos and on some web browsers in Windows NTLM is supported by default.  If a www-authenticate challenge comes from a server outside a browsers permitted list, users may encounter an NTLM dialog prompt.  A user would need to click the cancel button on the dialog to continue as Keycloak does not support this mechanism.  This situation can happen if Intranet web browsers are not strictly configured or if Keycloak serves users in both the Intranet and Internet.  A https://github.com/keycloak/keycloak/issues/8989[custom authenticator] can be used to restrict Negotiate challenges to a whitelist of hosts.
```

2023-02-22 14:00 UTC, andymunro requested changes
Thanks, just one change to suggest @slominskir

2023-02-22 14:35 UTC, mposolda approved these changes
@andymunro Thanks!

2023-02-22 14:47 UTC, merged