fix read-only user attributes configuration options
keycloak/keycloak-documentation pull request #1786
Opened 2023-02-24 15:53 UTC by onmomo

This cost me several hours of debugging and frustration. :-) I'm surprise that the setting already follows the upcoming declarative-user-profile even though this feature is still in preview?
Anyways, I managed to verify that the config is loaded with this updated settings with Keycloak 20.0.3.

`AbstractUserProfileProvider#init`
<img width="1072" alt="Screenshot 2023-02-24 at 14 49 08" src="https://user-images.githubusercontent.com/1713109/221224061-75b8ffc6-d730-4ade-980b-038935ab01d2.png">

2023-03-10 18:33 UTC, ahus1 approved these changes
Thank you for fixing this and sharing this and sorry it took so much time to find out about this!

2023-03-10 18:41 UTC, andymunro commented on server_admin/topics/threat/read-only-attributes.adoc
> +or leveraging environment variables
```suggestion
You can instead use environment variables. For example:
```

2023-03-10 18:42 UTC, andymunro requested changes
Approved pending one change.

2023-03-24 09:18 UTC, ahus1 commented
This has been fixed in issue https://github.com/keycloak/keycloak/issues/19122 in the main repository yesterday.

2023-03-24 09:18 UTC, closed without merging