Links to Quickstarts should use attribute
keycloak/keycloak-documentation pull request #1799
Opened 2023-03-10 09:18 UTC by ahus1

Closes #1798

2023-03-10 16:17 UTC, andymunro commented on authorization_services/topics/authorization-quickstarts.adoc
>  | A simple application based on HTML5+AngularJS+JAX-RS that demonstrates how to enable User-Managed Access to your application and let users to manage permissions for their resources.
```suggestion
| A simple application based on HTML5+AngularJS+JAX-RS that demonstrates how to enable User-Managed Access to your application and let users manage permissions for their resources.
```

2023-03-10 16:18 UTC, andymunro requested changes
Looks good.  Approved if one minor change is made.

2023-03-10 18:07 UTC, ahus1 commented
@andymunro - thanks for the review; I accepted your change. This is now ready for your final review.

2023-03-13 14:10 UTC, andymunro approved these changes

2023-03-14 10:57 UTC, merged