[KEYCLOAK-3482]
keycloak/keycloak-documentation pull request #323
Opened 2018-02-09 18:27 UTC by abstractj

2018-02-09 18:32 UTC, matthewhelmke requested changes
Thank you for doing this! I've edited the paragraph, so it should be a quick copy/paste update on your end.

2018-02-09 18:32 UTC, matthewhelmke commented on server_admin/topics/threat/admin.adoc
> +
Edit suggestion:
There are scenarios where it is desirable to hide the {project_name} version. To do so, create Undertow filters redirecting all the requests to `/auth/version` to any page you want, which will then prevent access to the details about the server. The following example prevents access to `/auth/version`:

2018-02-09 20:07 UTC, abstractj commented
@matthewhelmke thank you, updated.

2018-02-09 20:21 UTC, matthewhelmke approved these changes

2018-02-12 17:42 UTC, stianst commented
@abstractj I would just remove the endpoint in 7.3, but document for 7.2

2018-02-19 10:38 UTC, abstractj commented
Closing it and will do what Stian suggested.

2018-02-19 10:38 UTC, closed without merging