[KEYCLOAK-3169] - UMA 2.0 related changes
keycloak/keycloak-documentation pull request #325
Opened 2018-02-12 17:10 UTC by pedroigor

This PR contains changes that update docs accordingly with the upcoming changes to UMA v2 support. 

Some changes are basically removing UMA v1 references while others are including references to additional features and capabilities introduced by UMA v2.

2018-02-12 17:32 UTC, matthewhelmke commented
@pedroigor can you please ping me when the changes are about go be merged in the code? I don't think we want to merge this until that is happening. In the meanwhile, I will start reading through the changes and begin a review of the content. Thanks!!

2018-02-12 17:33 UTC, matthewhelmke commented
Also, @pedroigor , I assume there will be RH-SSO images coming that parallel the Keycloak images. Is that correct?

2018-02-12 18:37 UTC, pedroigor commented
@matthewhelmke this is the PR with the code changes https://github.com/keycloak/keycloak/pull/4368.

And yeah, I also need to include some RH-SSO images :)

2018-02-12 19:15 UTC, matthewhelmke requested changes
Don't be scared: many of the changes are just me noting multiple instances of the same issue, such as changing "a" to "an" and so on.

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/auth-services-architecture.adoc
> +
OAuth2 clients (such as front end applications) can obtain access tokens from the server using the token endpoint and use these same tokens to access resources protected by a resource server (such as back end services). In the same way, {project_name} Authorization Services provide extensions to OAuth2 to allow access tokens to be issued based on the processing of all policies associated with the resource(s) or scope(s) being requested. This means that resource servers can enforce access to their protected resources based on the permissions granted by the server and held by an access token. In {project_name} Authorization Services the access token with permissions is called a **R**equesting **P**arty **T**oken or **RPT** for short.

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/auth-services-architecture.adoc
> +The *Protection API* is a set of https://docs.kantarainitiative.org/uma/wg/oauth-uma-federated-authz-2.0-09.html[UMA-compliant] endpoint providing operations
"endpoint-providing"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/auth-services-architecture.adoc
> +for resource servers to help them manage their resources, scopes, permissions and policies associated with them. Only resource servers are allowed to access this API, which also requires a
You need a comma after "permissions"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/auth-services-terminology.adoc
> +structure represents the resources and/or scopes being requested by a client, the access context as well as the policies that must be applied to a request for authorization data (requesting party tok
You need a comma after "access context"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +* Obtain permissions from the server using a permission ticket, in case you are accessing a UMA protected resource server.
* Obtain permissions from the server using a permission ticket, if you are accessing a UMA protected resource server.

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +.Example about how to obtain a RPT with permissions for all resources and scopes the user can access
"an RPT", just a weird English language thing...

.Example: obtaining an RPT with permissions for all resources and scopes the user can access

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +```json
.Example: obtaining an RPT with permissions for specific resources and scopes

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +A boolean value indicating to the server if resource names should be included in the RPT's permissions. if false, only the resource
Capitalize "If false"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +An integer N that defines a limit for the amount of permissions a RPT can have. When used together with
"an RPT"

When used together with the `rpt` parameter...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-js-adapter.adoc
> +This parameter only have effect if used together with the `ticket` parameter as part of a UMA authorization process.
This parameter will only take effect when used together with the `ticket` parameter as part of a UMA authorization process.

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +{project_name} provides a discovery document from where clients can obtain all necessary information to interact with
...document from which...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +The discovery document can be obtained from the following location:
The discovery document can be obtained from:

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +A OAuth2 compliant Token Endpoint that supports the `urn:ietf:params:oauth:grant-type:uma-ticket` grant type. Through this
An OAuth2-compliant...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +A OAuth2 compliant Token Introspection Endpoint which clients can use to query the server to determine the active state of a RPT
An OAuth2-compliant...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +A UMA compliant Resource Registration Endpoint which resource servers can use to manage their protected resources and scopes. This endpoint provides
A UMA-compliant...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +operations create, read, update and delete resources and scopes in {project_name}.
You need a comma after "update"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-discovery-document.adoc
> +A UMA compliant Permission Endpoint which resource servers can use to manage permission tickets. This endpoint provides
A UMA-compliant...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +Clients need to authenticate to the token endpoint in order to obtain a RPT. When using the `urn:ietf:params:oauth:grant-type:uma-ticket`
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +.An authorization request using an access token to authenticate to the token endpoint
.Example: an authorization...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +.An authorization request using an access token to authenticate to the token endpoint
.Example: an authorization...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +This method is specially useful when the client is acting on behalf of an user.
...is especially useful...
...of a user. (another weird English language thing)

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +of an user (or on behalf of itself). Permissions will be evaluated considering the access context represented by the access token.
a user

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +For instance, if the access token was issue to Client A acting on behalf of User A, permissions will granted depending on
...was issued to...
...permissions will be granted...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-authentication.adoc
> +the resources and scopes User A has access.
...scopes to which User...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +Nowadays, user's privacy is becoming a huge concern, as more and more data and devices are available and connected to the cloud. With
remove the 's, just "user privacy"

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +to user's privacy where permissions are granted based on policies defined by the user.
user privacy

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +to access these resources. Different than OAuth2 where consent is given to a client application acting on behalf of an user, with UMA
This is different than OAuth2...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +resource owners are allowed to consent access to other users, in a complete asynchronous manner.
completely asynchronous

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +{project_name} can then act as a sharing management service from where resource owners can manage their resources.
from which

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +{project_name} is a UMA 2.0 compliant authorization server that provides most of UMA capabilities.
most UMA capabilities

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +As an example, consider an user Alice (resource owner) using a Internet Banking Service (resource server) to manage his Bank Account (resource). One day, Alice decides
a user
an Internet Banking Service

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +At this moment, if Bob tries to access Alice's Bank Account access will be denied. The Internet Banking Service defines a few default
...Bank Account, access...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission-uma.adoc
> +policies for banking accounts, one of them is that only the owner, in this case Alice, is allowed to access her bank account.
banking accounts. One of them

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +evaluate all policies associated with the resource(s) and scope(s) being requested and issue a RPT with all permissions
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +permissions for the resource(s) and scope(s) being requested. This parameter allow clients to push claims to {project_name}. For more details about all supported token formats see.
Missing the link here: "For more details about all supported token formats see."

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +This parameter is *optional. A string indicating the format of the token specified in the `claim_token` parameter. For more details about all supported token formats see.
link

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +allows clients in possession of a RPT to perform incremental authorization where permissions are added on demand.
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +This parameter is *optional*. A boolean value indicating to the server if resource names should be included in the RPT's permissions. if false, only the resource
...server whether resource names...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +This parameter is *optional*. An integer N that defines a limit for the amount of permissions a RPT can have. When used together with
...together with the...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +the `access_token` response parameter. In case the client is not authorized to have permissions {project_name} responds with a `403` HTTP status code:
If the client is not authorized, {project_name}...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +On the left side menu there is a `My Resources` option that leads to a page where users are able to:
...side menu, the `My Resources` option leads to...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +In this section, there is a list of all permission request waiting for user's approval. These request are related
This section contains a list of all permission requests awaiting approval. These requests are connected to the parties (users) requesting access to...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +In this section, there is a list of all resources owned by the user. Users can click on a resource for more details
This section contains a list...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +In this section, there is a list of all resources shared with the user.
This section contains a list...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +In this section, there is a list of permission requests sent by the user that are waiting for the approval of another user or
This section contains a list...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
> +In this section, there is a list of people with access to the resource. Users are allowed to revoke access by clicking
This section contains a list...

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-authz-process.adoc
> +A UMA protected resource server expects a bearer token in the request where the token is a RPT. When a client requests
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-authz-process.adoc
> +.Client requests a protected resource without sending a RPT
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-authz-process.adoc
> +of a {project_name} server to where the ticket should be sent in order to obtain a RPT.
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-authz-process.adoc
> +.Client sends an authorization request to the token endpoint to obtain a RPT
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-submiting-permission-requests.adoc
> +to exchange it with a RPT at the {project_name} Token Endpoint.
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-submiting-permission-requests.adoc
> +By default, {project_name} responds with a `403` HTTP status code and a `request_denied` error in case the client can not be issued with a RPT.
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-submiting-permission-requests.adoc
> +Such response implies that {project_name} could not issue a RPT with the permissions represented by a permission ticket.
an RPT

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-client-api.adoc
> +It is targeted for resource servers that want to access the different endpoints provided by the server such as the Token Endpoint, Resource and Permission management endpoints.
you need a comma after Resource

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-client-api.adoc
> +// create a new instance based on the configuration define at keycloak-authz.json
defined in

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-overview.adoc
> +{project_name} Authorization Services are built on top of well-known standards such as OAuth2 and User-Managed Access specifications.
such as the OAuth2

2018-02-12 19:15 UTC, matthewhelmke commented on authorization_services/topics/service-overview.adoc
> +Just like OAuth2 where clients (e.g.: frontend application) cab obtain access tokens from the server using the token endpoint and use these same tokens
clients (such as front end applications)

General rule: Red Hat standards require us to NOT use Latin-derived abbreviations like "e.g.". Instead, use "such as".

Same in the next line with back end services.

2018-02-14 12:56 UTC, matthewhelmke approved these changes

2018-02-27 10:06 UTC, mhajas approved these changes

2018-02-28 07:53 UTC, stianst approved these changes

2018-02-28 07:53 UTC, merged