[KEYCLOAK-4102] - Support lazy loading of paths via policy enforcer config
keycloak/keycloak-documentation pull request #349
Opened 2018-03-27 14:25 UTC by pedroigor

2018-03-27 15:15 UTC, matthewhelmke requested changes

2018-03-27 15:15 UTC, matthewhelmke commented on authorization_services/topics/enforcer-keycloak-enforcement-filter.adoc
>  +
Question about "should be protected": how is it known what "should" be protected? Is it more accurate to say "may be protected" or, in that case, perhaps leave the phrase out entirely?

Possible edit, maybe with [ ] phrase deleted:
Specifies the paths to protect. This configuration is optional. If not defined, the policy enforcer will discover all paths [that should be protected] by fetching the resources you defined to your application in {project_name}, where these resources are defined with a `URI` representing some path in your application.

2018-03-27 18:07 UTC, matthewhelmke approved these changes

2018-03-29 12:17 UTC, pedroigor commented
@matthewhelmke, upstream merged. Tks.

2018-03-29 12:18 UTC, merged