[KEYCLOAK-7029] - Configuration of cache policies for cached resource…
keycloak/keycloak-documentation pull request #356
Opened 2018-04-04 11:47 UTC by pedroigor

2018-04-04 11:53 UTC, matthewhelmke requested changes
One question with an easy fix.

2018-04-04 11:53 UTC, matthewhelmke commented on authorization_services/topics/enforcer-keycloak-enforcement-filter.adoc
> ++
Do we mean the cache "is a responsible way to avoid unnecessary requests" or that the cache "is needed to avoid..."?

2018-04-05 12:20 UTC, pedroigor commented on authorization_services/topics/enforcer-keycloak-enforcement-filter.adoc
> ++
That cache "is needed to avoid...".

2018-04-05 12:25 UTC, matthewhelmke commented on authorization_services/topics/enforcer-keycloak-enforcement-filter.adoc
> ++
Thanks. I suggest changing the sentence to "The cache is needed to avoid..." and we are good.

2018-04-05 12:36 UTC, pedroigor commented
@matthewhelmke, Changes made. Upstream PR already merged.

2018-04-05 12:38 UTC, matthewhelmke approved these changes
Thank you!

2018-04-05 12:40 UTC, merged