Add adapter option to keycloak.js
keycloak/keycloak-documentation pull request #359
Opened 2018-04-13 10:20 UTC by wtrocki

Adding documentation for adapter option.

2018-04-13 10:28 UTC, wtrocki commented
It seems that the build is failing due to missing link that is also broken on master. Going to fix that in this PR.

2018-04-13 12:32 UTC, matthewhelmke requested changes
Thank you. I have made some language edits during my review and posted them in a comment.

2018-04-13 12:32 UTC, matthewhelmke commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +    * custom - function that allows to implement custom adapter (only for advanced use cases)
adapter::
    Allows you to override the way that redirects and other browser-related functions will be handled by the library.
    Available options:
    * "default" - the library uses the browser api for redirects (this is the default)
    * "cordova" - the library will try to use the InAppBrowser cordova plugin to load keycloak login/registration pages (this is used automatically when the library is working in a cordova ecosystem)
    * custom - allows you to implement a custom adapter (only for advanced use cases)

2018-04-13 13:02 UTC, wtrocki commented
@matthewhelmke Thank you so much for reviewing that in so short notice.
I have applied your changes.

2018-04-18 11:40 UTC, matthewhelmke approved these changes

2018-04-20 07:18 UTC, stianst approved these changes

2018-04-20 07:18 UTC, merged