[KEYCLOAK-4903] - Pushed Claims and improvements to PEP
keycloak/keycloak-documentation pull request #363
Opened 2018-04-18 20:16 UTC by pedroigor

2018-04-19 12:10 UTC, matthewhelmke requested changes
Just a few small changes requested, otherwise, this looks good!

2018-04-19 12:10 UTC, matthewhelmke commented on authorization_services/topics/enforcer-claim-information-point.adoc
> +
A Claim Information Point (CIP) is responsible for resolving claims and pushing these claims to the {project_name} server in order to provide more information about the access context to policies. They can be defined as a configuration option to the `policy-enforcer` in order to resolve claims from different sources, such as:

2018-04-19 12:10 UTC, matthewhelmke commented on authorization_services/topics/enforcer-claim-information-point.adoc
> +
When pushing claims to the {project_name} server, policies can base decisions not only on who an user is but also by taking context and contents into account, based on who, what, why, when, where, and which for a given transaction. It is all about Contextual-based Authorization and how to use runtime information in order to support fine-grained authorization decisions.

2018-04-19 12:10 UTC, matthewhelmke commented on authorization_services/topics/enforcer-claim-information-point.adoc
> +
Here are several examples showing how you can extract claims from an HTTP request:

2018-04-19 12:10 UTC, matthewhelmke commented on authorization_services/topics/enforcer-claim-information-point.adoc
> +
Here are several examples showing how you can extract claims from an external HTTP Service:

2018-04-19 12:10 UTC, matthewhelmke commented on authorization_services/topics/enforcer-claim-information-point.adoc
> +
When processing requests, the policy enforcer will call the `MyClaimInformationPointProviderFactory.create` method in order to obtain an instance of `MyClaimInformationPointProvider`. When called, any configuration defined for this particular CIP provider (via `claim-information-point`) is passed as a map.

2018-04-20 19:06 UTC, matthewhelmke approved these changes

2018-04-30 15:14 UTC, pedroigor commented
@matthewhelmke, upstream merged.

2018-04-30 15:16 UTC, matthewhelmke commented
@stianst I am okay to merge, are you?

2018-04-30 15:32 UTC, stianst approved these changes

2018-04-30 15:34 UTC, merged