KEYCLOAK-7274 Hardcoded config in offline adapter installation scripts
keycloak/keycloak-documentation pull request #373
Opened 2018-05-02 10:14 UTC by vramik

2018-05-02 10:40 UTC, vramik commented
https://github.com/keycloak/keycloak/pull/5184

2018-05-02 11:35 UTC, matthewhelmke submitted a review, later dismissed

2018-05-02 11:35 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> +Alternatively, you don't have to modify your WAR at all and you can secure it via the {project_name} adapter subsystem configuration in configuration file (e.g. `standalone.xml`).
...configuration in the configuration file, such as `standalone.xml`.

2018-05-02 11:35 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> +NOTE: To be able to perform substitution for command line properties it has to be set `resolve-parameter-values` to `true` in `./bin/jboss-cli.xml`
...command line properties you must set...

2018-05-02 11:49 UTC, matthewhelmke submitted a review, later dismissed
Looks good to me. Thank you!

2018-05-03 09:17 UTC, vramik commented
@matthewhelmke I've updated the PR because it was found out there is no need to edit jboss-cli.xml file. Can you pls check the changes again?

2018-05-03 11:45 UTC, matthewhelmke requested changes
Simple language adjustments

2018-05-03 11:45 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> +
NOTE: Alternatively, you can specify the `server.config` property while installing adapters from the command line to install adapters using a different config, for example: `-Dserver.config=standalone-ha.xml`.

2018-05-03 11:45 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
>  Both methods are described in this section.
...in the configuration file, such as...

2018-05-03 11:54 UTC, vramik commented
@matthewhelmke thank you

2018-05-03 11:57 UTC, matthewhelmke approved these changes

2018-05-03 12:47 UTC, stianst approved these changes

2018-05-03 17:50 UTC, merged