KEYCLOAK-7295 Additional troubleshooting info
keycloak/keycloak-documentation pull request #375
Opened 2018-05-03 06:24 UTC by hmlnarik

2018-05-03 06:42 UTC, mposolda submitted a review, later dismissed

2018-05-03 06:49 UTC, mposolda submitted a review, later dismissed

2018-05-03 11:42 UTC, matthewhelmke requested changes
Simple grammar changes

2018-05-03 11:42 UTC, matthewhelmke commented on server_installation/topics/operating-mode/crossdc.adoc
> ++
* If the {jdgserver_name} `work` cache grows indefinitely, you may be experiencing https://issues.jboss.org/browse/JDG-987[this {jdgserver_name} issue], which is caused by cache items not being properly expired. In that case, update the cache declaration with an empty `<expiration />` tag like this:

2018-05-03 14:20 UTC, hmlnarik commented on server_installation/topics/operating-mode/crossdc.adoc
> ++
Thanks! Fixed according to your suggestion.

2018-05-03 14:37 UTC, matthewhelmke approved these changes

2018-05-04 07:16 UTC, hmlnarik commented
Thanks for the reviews!

2018-05-04 07:17 UTC, merged