[KEYCLOAK-7552] - Improvements to AuthZ Quickstarts and Docs
keycloak/keycloak-documentation pull request #402
Opened 2018-06-12 02:19 UTC by pedroigor

2018-06-12 11:50 UTC, matthewhelmke requested changes
Looks good, just small changes being requested.

2018-06-12 11:50 UTC, matthewhelmke commented on authorization_services/topics/policy-js-policy.adoc
> +You can also check for realm roles granted to an user:
s/You can also/To

2018-06-12 11:50 UTC, matthewhelmke commented on authorization_services/topics/policy-js-policy.adoc
> +
s/You can also/To

2018-06-12 11:50 UTC, matthewhelmke commented on authorization_services/topics/policy-js-policy.adoc
> +You can push arbitrary claims to the resource server in order to provide additional information on how permissions should be
s/You can/To

2018-06-12 18:46 UTC, pedroigor commented
It seems that errors in travis are unrelated

2018-06-13 11:40 UTC, matthewhelmke requested changes

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/enforcer-keycloak-enforcement-filter.adoc
> +Specifies that the adapter uses the UMA protocol. If specified, the adapter queries the server for permission tickets and return them to clients according to the UMA specification. If not specified,
"...adapter queries the server for permission tickets and returns them..."

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To update an existing permission, you can send a HTTP PUT request as follows:
To update an existing permission, send an HTTP PUT request as follows:

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To remove a permission associated with a resource, you can send an HTTP DELETE request as follows:
remove "you can"

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To query the permissions associated with a resource, you can send an HTTP GET request as follows:
remove "you can"

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To query the permissions given its name, you can send an HTTP GET request as follows:
remove "you can"

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To query the permissions associated with a specific scope, you can send an HTTP GET request as follows:
remove "you can"

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +To query all permissions, you can send an HTTP GET request as follows:
remove "you can"

2018-06-13 11:40 UTC, matthewhelmke commented on authorization_services/topics/service-protection-policy-api.adoc
> +When querying the server for permissions you can also use parameters `first` and `max` results to limit the result.
remove "you can also"

2018-06-22 12:30 UTC, matthewhelmke commented
@pedroigor did all my requested changes make it in?

2018-06-22 14:06 UTC, pedroigor commented
@matthewhelmke, yes :)

2018-06-22 14:16 UTC, matthewhelmke submitted a review, later dismissed

2018-06-22 19:08 UTC, matthewhelmke requested changes
Looks good, thanks! Two very small changes being requested.

2018-06-22 19:08 UTC, matthewhelmke commented on authorization_services/topics/service-protection-resources-api-papi.adoc
> +
...an HTTP...

2018-06-22 19:08 UTC, matthewhelmke commented on authorization_services/topics/service-protection-resources-api-papi.adoc
> +specific user, you can send a request as follows:
...different owner, such as...

2018-06-22 19:57 UTC, pedroigor commented
@matthewhelmke, I have added the last two commits after your last review. They are adding more references to other parts of the documentation.

2018-06-25 12:58 UTC, matthewhelmke approved these changes

2018-06-25 12:58 UTC, matthewhelmke commented
Thanks, @pedroigor

2018-06-26 11:52 UTC, merged