[KEYCLOAK-7552] - Documentation on how to enable My Resources in account service
keycloak/keycloak-documentation pull request #415
Opened 2018-06-27 14:03 UTC by pedroigor

2018-06-27 15:12 UTC, matthewhelmke requested changes
Just a couple of minor changes.

2018-06-27 15:12 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-uma-account-my-resources.adoc
Users can manage access to their resources using the {project_name} User Account Service. To enable this functionality, you must first enable `User-Managed Access` for your realm. To do so, open the realm settings page in {project_name} Administration Console and enable the `User-Managed Access` switch.

2018-06-29 13:47 UTC, pedroigor commented
@stianst can you approve, please ?

2018-06-29 13:50 UTC, matthewhelmke approved these changes

2018-06-29 13:52 UTC, merged

2018-06-29 13:52 UTC, pedroigor commented
@matthewhelmke, tks !