KEYCLOAK-7703 Documentation for HierarchicalPathBasedKeycloakConfigResolver
keycloak/keycloak-documentation pull request #430
Opened 2018-07-18 15:30 UTC by hmlnarik

Documentation for keycloak/keycloak#5319

2018-07-18 15:41 UTC, matthewhelmke requested changes
Overall, this is clear and easy to read and understand. I have only some small changes to request.

2018-07-18 15:41 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/fuse7/classic-war.adoc
> +actual source of the configuration file, set `keycloak.config.resolver` deployment parameter to the desired configuration resolver class.
Should read "...set the `keycloak.config.resolver` deployment..."

2018-07-18 15:41 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/fuse7/classic-war.adoc
> +
I suggest: "The following resolvers are available for `keycloak.config.resolver`:

2018-07-18 15:41 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/fuse7/classic-war.adoc
> +  is configured from. By default, it loads file named `WEB-INF/keycloak.json` but this file name can be configured via `configLocation` property.
I am unclear what is being said in "Default resolver that looks up for the configuration file inside the bundle it is configured from."

Are you trying to say this? "This is the default resolver, which requires a configuration file. By default, it loads..."

2018-07-18 15:41 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/fuse7/classic-war.adoc
> +  It searches for a file called `<your_web_context>-keycloak.json` inside a folder
I suggest starting this with "This resolver searches for a file..."

2018-07-18 15:41 UTC, matthewhelmke commented on securing_apps/topics/oidc/java/fuse7/classic-war.adoc
> +  Similar to `PathBasedKeycloakConfigResolver` above, where for given URI path,
I suggest starting with a parallel phrase, such as "This resolver is similar to..."

2018-07-18 18:59 UTC, hmlnarik commented
Thanks @matthewhelmke for your comments!

2018-07-19 05:24 UTC, pdrozd approved these changes

2018-07-20 11:15 UTC, matthewhelmke approved these changes

2018-07-20 19:40 UTC, merged