KEYCLOAK-7888 Better way of securing CXF deployments
keycloak/keycloak-documentation pull request #431
Opened 2018-07-19 13:18 UTC by hmlnarik

2018-07-19 13:23 UTC, grgrzybek commented on securing_apps/topics/oidc/java/fuse7/cxf-builtin.adoc
> +Some services automatically come with deployed servlets on startup. One such service is the CXF servlet running in the $$http://localhost:8181/cxf$$ context. Fuse's Pax Web supports context configura
_context configuration_ is not precise - it's rather _altering_/_processing_ of existing contexts. You can refer to https://ops4j1.jira.com/wiki/spaces/paxweb/pages/354025473/HTTP+Context+processing

2018-07-19 13:26 UTC, grgrzybek requested changes

2018-07-19 13:26 UTC, grgrzybek commented on securing_apps/topics/oidc/java/fuse7/cxf-builtin.adoc
> +Some services automatically come with deployed servlets on startup. One such service is the CXF servlet running in the $$http://localhost:8181/cxf$$ context. Fuse's Pax Web supports context configura
_context configuration_ is not precise - it's rather _altering_/_processing_ of existing contexts. You can refer to https://ops4j1.jira.com/wiki/spaces/paxweb/pages/354025473/HTTP+Context+processing

2018-07-19 13:26 UTC, grgrzybek commented on securing_apps/topics/oidc/java/fuse7/cxf-builtin.adoc
> +The `Import-Package` in `META-INF/MANIFEST.MF` must contain at least these imports:
In fact, I didn't have to add any explicit imports for `org.keycloak` packages of my bundle containing blueprint-based CXF endpoints. pax-web's processing is fully external to your bundle (and to CXF).

2018-07-20 11:26 UTC, matthewhelmke approved these changes
Looks good to me.

2018-07-20 19:42 UTC, merged