KEYCLOAK-6818 Extra AUTH_SESSION_ID cookie with a path of /auth
keycloak/keycloak-documentation pull request #441
Opened 2018-08-09 13:00 UTC by martin-kanis

2018-08-09 13:09 UTC, mposolda submitted a review, later dismissed
LGTM

Adding also @hmlnarik and @matthewhelmke for review.

2018-08-09 13:21 UTC, matthewhelmke requested changes
I have suggested some language-related edits.

2018-08-09 13:21 UTC, matthewhelmke commented on server_installation/topics/clustering/sticky-sessions.adoc
> +
A couple small edits:

WARNING: Use the `session-config` only with the mod_cluster load balancer. In other cases, configure sticky session over the `AUTH_SESSION_ID` cookie directly in a load balancer.

2018-08-09 13:21 UTC, matthewhelmke commented on server_installation/topics/clustering/sticky-sessions.adoc
> +WARNING: You should always access the cluster through load balancer and not through backend node directly, when using mod_cluster.
Minor edits:
WARNING: When using mod_cluster you should always access the cluster through the load balancer and not directly through the backend node.

2018-08-09 13:55 UTC, martin-kanis commented
@matthewhelmke fixed, thank you

2018-08-09 13:59 UTC, matthewhelmke approved these changes

2018-08-10 06:51 UTC, hmlnarik approved these changes
LGTM, thanks!

2018-08-10 06:51 UTC, merged