[KEYCLOAK-4902] - Response_mode parameter and release notes for authorization services
keycloak/keycloak-documentation pull request #442
Opened 2018-08-10 12:43 UTC by pedroigor

2018-08-10 13:00 UTC, matthewhelmke requested changes
This looks good to me. I found one typing mistake that needs to be fixed, but otherwise, this is ready.

2018-08-10 13:00 UTC, matthewhelmke commented on authorization_services/topics/service-authorization-obtaining-permission.adoc
> +you are mainly interested on either the overall decision or the permissions granted by the server, instead of an standard OAuth2 response. Possible values are:
Should be "...mainly interested in..."

2018-08-10 18:19 UTC, matthewhelmke submitted a review, later dismissed

2018-08-14 09:43 UTC, stianst approved these changes

2018-08-14 09:54 UTC, stianst commented
Sorted out merge conflicts in new PR here: https://github.com/keycloak/keycloak-documentation/pull/446

2018-08-14 09:54 UTC, closed without merging