[KEYCLOAK-8129] Describe the newly introduced SSO_HOSTNAME environment variable
keycloak/keycloak-documentation pull request #455
Opened 2018-08-28 12:18 UTC by iankko

Also add additional steps to 'Advanced Concepts' section, on how
to configure `fixed` hostname SPI provider

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

2018-08-28 12:18 UTC, iankko commented
@matthewhelmke @stianst @Crumby PTAL (once got a chance)

Thank you, Jan

2018-08-28 13:40 UTC, matthewhelmke requested changes
Only one very small change to request. Nicely done!

2018-08-28 13:40 UTC, matthewhelmke commented on openshift/content/advanced_concepts/advanced_concepts.adoc
> +. Change its `host:` field to match the hostname specified as the value of the *_SSO_HOSTNAME_* environment variable above.
Instead of "Change its..." use "Change the...".

2018-08-28 14:13 UTC, iankko commented
@matthewhelmke Thanks, Matthew! Fixed and squashed into the previous commit.

2018-08-28 14:47 UTC, matthewhelmke submitted a review, later dismissed

2018-09-24 19:43 UTC, stianst submitted a review, later dismissed

2018-10-24 18:24 UTC, matthewhelmke commented
@stianst I still approve.
@iankko Can you please resolve the conflicts so we can merge?

2018-10-25 12:36 UTC, matthewhelmke commented
@iankko FYI, I looked at the conflict and was not sure which of the options was the correct one; this is why I am asking you to please resolve the conflict.

2018-11-13 12:13 UTC, matthewhelmke commented
@stianst @iankko 
I took another pass at this and figured out what I believe is the conflict and correct resolution, but when I pushed, it pushed to my fork's master [1]. How do I merge that in here so we can move on?

[1] https://github.com/matthewhelmke/keycloak-documentation/commit/64d3de465730a0b69644820155a3eca818928433

2018-11-14 14:53 UTC, iankko commented
@matthewhelmke @stianst  Fixed the conflict & rebased to current master. Should be again ready for review. Sorry for the delay.

2018-11-14 14:55 UTC, matthewhelmke approved these changes
Thank you, @iankko

2018-12-04 17:21 UTC, stianst approved these changes

2018-12-17 07:19 UTC, stianst approved these changes

2018-12-18 12:24 UTC, matthewhelmke commented
Thank you, @iankko .

2018-12-18 12:24 UTC, merged