Patch about auth and token endpoint
keycloak/keycloak-documentation pull request #459
Opened 2018-08-30 14:29 UTC by jolisylvain

I think the definitions of auth and token OIDC endpoints have been inverted

2018-08-30 15:23 UTC, matthewhelmke approved these changes
Thank you! This looks fine to me, but I will defer to engineering for confirmation.

2018-09-24 19:59 UTC, stianst commented
Actually, it's both inverted and also wrong. The auth endpoint is for the authorization code flow that's correct, but not for obtaining tokens via implicit flow, direct grant or client grants. All requests that obtain tokens use the token endpoint.

2018-09-24 19:59 UTC, stianst requested changes
See comment

2018-12-04 18:11 UTC, stianst commented
Closing this as it's incorrect and there is no feedback from contributor. Feel free to re-open once comments have been addressed.

2018-12-04 18:11 UTC, closed without merging