[KEYCLOAK-6962] Added ways to (minor) upgrade rpm distribution
keycloak/keycloak-documentation pull request #466
Opened 2018-09-04 11:49 UTC by pskopek

https://issues.jboss.org/browse/KEYCLOAK-6962

2018-09-04 13:00 UTC, matthewhelmke commented
We have information in https://github.com/keycloak/keycloak-documentation/blob/master/upgrading/topics/rhsso/patching-rpm-installation.adoc for updating via RPMs. This topic is RH-SSO only, as Keycloak is not distributed/updated using RPMs. It looks like what you have written may overlap and expand upon what we already have here. Can you compare the two and see how to merge the information?

2018-09-04 13:11 UTC, pskopek commented
@matthewhelmke the topic you mentioned is for micro upgrade (or patching). There is no need to do anything with already subscribed repositories and it is correct. 
The one from this section describes minor upgrade (7.1 -> 7.2).

2018-09-04 14:31 UTC, matthewhelmke submitted a review, later dismissed
Got it. Thank you, @pskopek . This looks good.

2018-09-05 07:00 UTC, hmlnarik requested changes
Good point @matthewhelmke, we have to enclose the RPM-related stuff into `ifeval::[{project_product}==true]` similarly to https://github.com/keycloak/keycloak-documentation/blob/0e8b9a7ac2207db7b4dedb8be95413c7a18e6eb7/upgrading/topics.adoc.

In the meantime, @wyvie could you please have a look at this PR?

2018-09-05 07:39 UTC, pskopek commented
@hmlnarik good catch, fixed

2018-09-05 08:26 UTC, alicerum reviewed
otherwise all seems good

2018-09-05 08:26 UTC, wyvie commented on upgrading/topics/install_new_version.adoc
> + Use to disable older product repositories for both JBOSS EAP and {project_name} use:
two times 'use' here. First one could possibly be removed

2018-09-05 08:34 UTC, pskopek commented
Thnks @wyvie, fixed.

2018-09-05 09:04 UTC, hmlnarik requested changes

2018-09-05 09:04 UTC, hmlnarik commented on upgrading/topics/install_new_version.adoc
> +NOTE:
This does not render correctly to an info box. The `NOTE: ` has to be followed by text, otherwise it renders just as "NOTE: " text.

2018-09-05 11:51 UTC, hmlnarik approved these changes

2018-09-05 11:52 UTC, hmlnarik commented
@pskopek Thanks for changes, @matthewhelmke, @wyvie Thanks for review!

2018-09-05 11:52 UTC, merged