Release notes update for token signatures
keycloak/keycloak-documentation pull request #474
Opened 2018-09-11 06:33 UTC by stianst

2018-09-11 11:46 UTC, matthewhelmke requested changes
Looks good. I have a couple edit suggestions for greater effect.

2018-09-11 11:46 UTC, matthewhelmke commented on release_notes/topics/4_5_0_final.adoc
> +security properties as RSA signatures, but uses significantly less CPU.
Should be "...but use significantly less..."

2018-09-11 11:46 UTC, matthewhelmke commented on release_notes/topics/4_5_0_final.adoc
> +
The Signature SPI makes it possible to plug-in additional signature algorithms. This enables additional signatures and also enables changing how signatures are generated. For example, using this allows using an HSM device to sign tokens.

2018-09-24 19:52 UTC, merged

2018-09-24 19:52 UTC, stianst commented
Updated suggestions and merged to make sure it's included in the 4.5 release