KEYCLOAK-6884 KEYCLOAK-3454 KEYCLOAK-8298 Documentation for default '…
keycloak/keycloak-documentation pull request #487
Opened 2018-10-03 13:03 UTC by mposolda

…roles' and 'web-origins' client scopes

2018-10-03 13:04 UTC, mposolda commented
Implementation PR: https://github.com/keycloak/keycloak/pull/5602

2018-10-03 13:19 UTC, matthewhelmke requested changes
I have just a few changes to clean and polish this.

2018-10-03 13:19 UTC, matthewhelmke commented on server_admin/topics/clients/client-scopes.adoc
> +Client scope `roles` is not defined in the OpenID Connect specification and it is also not added automatically to the `scope`
Should be "The client scope `roles` is..."

2018-10-03 13:19 UTC, matthewhelmke commented on server_admin/topics/clients/client-scopes.adoc
> +`web-origins` .
There is an extra space before the period at the end of this sentence.

2018-10-03 13:19 UTC, matthewhelmke commented on server_admin/topics/clients/client-scopes.adoc
> +Client scope `web-origins` is also not defined in the OpenID Connect specification and not added to the `scope` claim. This is used
Also needs a "The" at the beginning.

2018-10-03 13:19 UTC, matthewhelmke commented on server_admin/topics/clients/oidc/audience.adoc
> +
[[_audience_resolve]]
===== Automatically add audience
There is another way that the audience can be added to the token. In the default client scope _roles_, there is an _Audience Resolve_ protocol mapper defined. This protocol mapper will check all the clients for which current token has at least one client role available. Then the client ID of each of those clients will be added as an audience automatically. This is especially useful if your service (usually bearer-only) clients rely on client roles. In the example in previous section, if all of those are true:
* The `good-service` client has any client role defined on itself
* Target user has this client role assigned
* Client `my-app` has the role scope mappings for this role
then the `good-service` will be automatically added as an audience. In this case, you do not need to set up the audience client scope as described in the previous section.
NOTE: If you are unsure what the correct audience and roles in the token will be, it is always a good idea to
<<_client_scopes_evaluate, Evaluate Client Scopes>> in the admin console and do some testing around it.

2018-10-03 13:19 UTC, matthewhelmke commented on upgrading/topics/keycloak/changes.adoc
> +
=== Migrating to 4.6.0
==== New default client scopes
We have added new realm default client scopes `roles` and `web-origins`. These client scopes contain protocol
mappers to add the roles of the user and allowed web origins to the token. During migration, these client scopes should be automatically added to all the OpenID Connect clients as default client scopes. Hence no setup should be required after database migration is finished.
===== Protocol mapper SPI addition
Related to this, there is a small addition in the (unsupported) Protocol Mappers SPI. You can be affected only if you
implemented a custom ProtocolMapper. There is a new `getPriority()` method on the ProtocolMapper interface. The method has the default implementation set to return 0. If your protocol mapper implementation relies on the roles in the access token `realmAccess` or `resourceAccess` properties, you may need to increase the priority of your mapper.
===== Audience resolving
Audiences of all the clients, for which authenticated user has at least one client role in the token, are automatically added to the `aud` claim in the access token now.

2018-10-03 13:48 UTC, mposolda commented
@matthewhelmke I've updated PR per your feedback. Thanks!

2018-10-03 13:52 UTC, matthewhelmke approved these changes

2018-10-04 07:30 UTC, stianst reviewed
-

2018-10-04 07:31 UTC, stianst reviewed
Should we not document the priority for the built-in providers that define one?

2018-10-04 07:46 UTC, mposolda commented
@stianst Maybe yes. But I figure we don't have any documentation for protocolMappers and hence we don't have docs also for ProtocolMapper providers and what each provider is doing :) Should I add some documentation for this as part of this PR?

2018-10-04 07:49 UTC, stianst commented
It's probably out of scope of this PR to document all protocol mapppers, but would at least be good to highlight those where the priority matters. Otherwise people will have no clue on how to use priority to make sure their mappers are executed at the right points.

2018-10-04 09:12 UTC, stianst commented
Added follow-up issue to document protocol mapper priorities:
* https://issues.jboss.org/browse/KEYCLOAK-8485

2018-10-04 09:13 UTC, stianst approved these changes

2018-10-04 10:02 UTC, merged