KEYCLOAK-8300 Wildfly 14 upgrade
keycloak/keycloak-documentation pull request #500
Opened 2018-10-16 16:19 UTC by mposolda

2018-10-16 16:25 UTC, matthewhelmke requested changes
This is quite good. I have a couple small edits to request here.

2018-10-16 16:25 UTC, matthewhelmke commented on server_installation/topics/clustering/sticky-sessions.adoc
> +start up command with this system property can look like this:
I would prefer the introduction to say:
"Here is an example of the start up command using this system property:"

2018-10-16 16:25 UTC, matthewhelmke commented on server_installation/topics/clustering/sticky-sessions.adoc
>  for example if you want to hide the host name of your {project_name} server inside your private network.
Typically in production environment the route name should use the same name as your backend host, but it is not required. You can use a different route name. For example, if you want to hide the host name of your {project_name} server inside your private network.

2018-10-16 16:25 UTC, matthewhelmke commented on server_installation/topics/operating-mode/crossdc.adoc
> +and you see some similar errors in the {project_name} log, it can indicate that there are incompatible versions of HotRod protocol used.
...it can indicate that there are incompatible versions of the HotRod protocol being used.

2018-10-16 16:25 UTC, matthewhelmke commented on server_installation/topics/operating-mode/crossdc.adoc
> +For example like this:
This is likely happen when you try to use {project_name} with the JDG 7.2 server or an old version of the Infinispan server. It will help if you add the `protocolVersion` property as an additional property to the `remote-store` element in the {project_name} configuration file.
For example:

2018-10-16 19:00 UTC, mposolda commented
@matthewhelmke Thanks for the review! I've updated the PR as you suggested.

2018-10-16 19:07 UTC, matthewhelmke approved these changes

2018-10-17 08:27 UTC, stianst approved these changes

2018-10-17 08:32 UTC, hmlnarik approved these changes

2018-10-17 18:12 UTC, merged