KEYCLOAK-8484 Audience changes due removing client scope template
keycloak/keycloak-documentation pull request #505
Opened 2018-10-25 19:40 UTC by mposolda

2018-10-25 19:41 UTC, mposolda commented
Codebase PR: https://github.com/keycloak/keycloak/pull/5672

2018-10-25 20:06 UTC, matthewhelmke requested changes
This is really well done. I only have a few edits to request.

2018-10-25 20:06 UTC, matthewhelmke commented on server_admin/topics/clients/oidc/audience.adoc
> +are true:
Instead of "If all of those are true:" let's say "If the following are true:"

2018-10-25 20:06 UTC, matthewhelmke commented on server_admin/topics/clients/oidc/audience.adoc
> +NOTE: If you want to ensure that audience is not added automatically, it may be good idea to not configure role scope mappings directly
...is not added automatically, do not configure...

2018-10-25 20:06 UTC, matthewhelmke commented on server_admin/topics/clients/oidc/audience.adoc
> +For the case when your service rely on realm roles or does not rely on the roles in the token at all, it can be useful to use hardcoded
...when your service relies on realm notes...

2018-10-25 20:06 UTC, matthewhelmke commented on server_admin/topics/clients/oidc/audience.adoc
> +of the OpenID Connect specification. On the other hand, the access token does not necessarily has the client ID of the client,
...does not necessarily have the client ID...

2018-10-25 20:06 UTC, matthewhelmke commented on upgrading/topics/keycloak/changes.adoc
...to the `aud` claim in the access token now. On the other hand, an access token may not automatically contain the audience of the frontend client, for which it was issued. Read the link:{adminguide_link}#_audience[{adminguide_name}] for more details.

2018-10-26 06:41 UTC, mposolda commented
@matthewhelmke Applied your suggestions. Thanks a lot for them!

2018-10-26 11:22 UTC, matthewhelmke approved these changes

2018-10-31 06:24 UTC, stianst approved these changes

2018-10-31 10:11 UTC, merged