KEYCLOAK-8175 Client scopes permissions
keycloak/keycloak-documentation pull request #506
Opened 2018-10-25 19:59 UTC by mposolda

2018-10-25 19:59 UTC, mposolda commented
Codebase PR: https://github.com/keycloak/keycloak/pull/5670

2018-10-25 20:10 UTC, matthewhelmke requested changes
Again, very few corrections, but it was such a short passage that I copied/pasted/edited and pasted the new version into a comment.

2018-10-25 20:10 UTC, matthewhelmke commented on server_admin/topics/clients/client-scopes.adoc
> +
When issuing tokens for a particular user, the client scope is applied only if the user is permitted to use it. In the case that
a client scope does not have any role scope mappings defined on itself, then each user is automatically permitted to use this client scope. However, when a client scope has any role scope mappings defined on itself, then the user must be a member of at least one of the roles. In other words, there must be an intersection between the user roles and the roles of the client scope. Composite roles are taken into account when evaluating this intersection. If a user is not permitted to use the client scope, then no protocol mappers or role scope mappings will be used when generating tokens and the client scope will not appear in the _scope_ value in the token.

2018-10-26 06:23 UTC, mposolda commented
@matthewhelmke Thanks! I've applied your suggestions. However I still kept two paragraphs. I guess you didn't mean to merge it into single paragraph, but it's just the github showing the comment in single paragraph? Let me know and I will merge into single paragraph if it's not the case and you think that single paragraph is better.

2018-10-26 11:21 UTC, matthewhelmke commented
@mposolda You are correct. I intended to leave the two paragraphs separate.

2018-10-26 11:22 UTC, matthewhelmke approved these changes

2018-10-31 17:05 UTC, merged