[KEYCLOAK-8694] - Mark Drools policy as tech preview
keycloak/keycloak-documentation pull request #511
Opened 2018-11-07 15:21 UTC by pedroigor

2018-11-07 18:38 UTC, matthewhelmke reviewed
One question in the comment above, otherwise LGTM.

2018-11-07 18:38 UTC, matthewhelmke commented on release_notes/topics/4_6_0_final.adoc
>  endif::[]
@pedroigor It looks like we have two `endif::[]` statements in here, your new one and an existing one on line 19. Am I reading that wrong?

2018-11-08 07:34 UTC, stianst requested changes

2018-11-08 07:34 UTC, stianst commented on topics/templates/techpreview.adoc
> +To enable start the server with `-Dkeycloak.profile=preview` or `{tech_feature_setting}`. For more details see
I assume techpreview.adoc is used elsewhere and those other places would not set tech_feature_setting currently

2018-11-19 12:40 UTC, matthewhelmke submitted a review, later dismissed

2018-12-04 18:15 UTC, stianst approved these changes

2018-12-13 07:45 UTC, merged