KEYCLOAK 8735 - updates to upgrade guide
keycloak/keycloak-documentation pull request #520
Opened 2018-11-16 13:22 UTC by matthewhelmke

These changes are for the upcoming 7.3 release of RH-SSO. I have based my changes here on the changes noted in the Keycloak docs for 4.0.0 through 4.6.0.

I _think_ I have captured everything, but would appreciate some help from engineering to review and check all the details. Also, if I missed anything I don't know what it is and would love a nudge in the right direction.

2018-11-16 13:23 UTC, matthewhelmke commented
I see this picked up some commits from @iankko . I do not know why. I did a fetch/rebase before making my changes which seemed to go normally. Then I turned around and pushed this fairly quickly. Odd.

2018-11-16 13:39 UTC, iankko commented
@matthewhelmke AFAICT the possible reason how this could happen is before you have pushed the KEYCLOAK-8129 changes to your master per this comment:
  https://github.com/keycloak/keycloak-documentation/pull/455#issuecomment-438245158

and if you then created KEYCLOAK-8735 branch from your master, the previous KEYCLOAK-8129 commits were still there.

In any case, you can drop the two KEYCLOAK-8129 related commits (updated my PR, so they will arrive within my KEYCLOAK-8129  change), and keep in your PR just the 3rd commit.

2018-11-16 13:43 UTC, matthewhelmke commented
@iankko that makes sense. I had forgotten that I had done that when I saw your PR update. Thank you.

I'll research how to drop the unrelated commits from this PR.

2018-11-16 13:46 UTC, matthewhelmke commented
Got it figured out. Thanks, again, @iankko.

@stianst I believe this is ready for review, with the original comment still in force.

2018-12-04 17:28 UTC, stianst requested changes
Items should be listed in priority order:

* Authorization Services
* Client Scope
* Upgrade to EAP 7.2 
* Hostname configuration
* JavaScript adapter promise
* Microsoft Identity Provider

2018-12-04 17:28 UTC, stianst commented on upgrading/topics/rhsso/changes-73.adoc
> +=== Upgrade to Wildfly 14
This needs to be changed to EAP 7.2. Same with references below to WF14.

2018-12-04 17:28 UTC, stianst commented on upgrading/topics/rhsso/changes-73.adoc
> +=== Client Templates changed to Client Scopes
Should combine all sections for client scopes into a single section

2018-12-04 20:45 UTC, matthewhelmke commented
I will work on this one first thing tomorrow morning.

2018-12-05 14:56 UTC, matthewhelmke commented
@stianst The new commit includes all requested changes.

2018-12-12 14:06 UTC, stianst approved these changes

2018-12-12 14:07 UTC, merged