[KEYCLOAK-8872] Keycloak 4.6.0.Final Script authenticator is missing
keycloak/keycloak-documentation pull request #527
Opened 2018-11-26 13:12 UTC by abstractj

2018-11-26 13:20 UTC, matthewhelmke requested changes
Just a couple minor things to request.

2018-11-26 13:20 UTC, matthewhelmke commented on server_admin/topics/authentication/flows.adoc
> +For more information see link:{installguide_profile_link}[{installguide_profile_name}] section.
You need a comma and a "the" here:
For more information, see the...

2018-11-26 13:27 UTC, abstractj commented
@matthewhelmke thank you! Updated.

2018-11-26 13:30 UTC, matthewhelmke approved these changes
Thank you.

2018-11-27 12:39 UTC, mposolda approved these changes

2018-12-04 13:34 UTC, mposolda commented
@matthewhelmke Could this be merged? I am not merging as it's assigned to you.

2018-12-04 13:40 UTC, matthewhelmke commented
@mposolda yes, I'll merge it now.

2018-12-04 13:40 UTC, merged