[KEYCLOAK-9016] Document the client mapper to make Gatekeeper with the latest Keycloak releases
keycloak/keycloak-documentation pull request #548
Opened 2018-12-14 10:36 UTC by abstractj

2018-12-14 12:20 UTC, matthewhelmke requested changes
I made a few minor edits in the Known Issues entry. Otherwise, LGTM.

2018-12-14 12:20 UTC, matthewhelmke commented on securing_apps/topics/oidc/keycloak-gatekeeper.adoc
> +* There is a known issue with Keycloak server 4.7.0.Final in which Gatekeeper won't be able to find the _client_id_ in _aud_ claim. This is due to the fact the _client_id_ is not in the audience anym
==== Known Issues
* There is a known issue with the Keycloak server 4.7.0.Final in which Gatekeeper is unable to find the _client_id_ in the _aud_ claim. This is due to the fact the _client_id_ is not in the audience anymore. The workaround is to add the "Audience" protocol mapper to the client with the audience pointed to the _client_id_. For more information, see link:https://issues.jboss.org/browse/KEYCLOAK-8954[KEYCLOAK-8954].

2018-12-14 13:36 UTC, matthewhelmke approved these changes

2018-12-14 13:44 UTC, slaskawi approved these changes

2018-12-14 13:50 UTC, hmlnarik approved these changes

2018-12-14 16:02 UTC, merged

2020-02-21 14:04 UTC, nngo commented on securing_apps/topics/oidc/keycloak-gatekeeper.adoc
> +* There is a known issue with the Keycloak server 4.7.0.Final in which Gatekeeper is unable to find the _client_id_ in the _aud_ claim. This is due to the fact the _client_id_ is not in the audience
Should the server version be 4.6.0.Final (as per KEYCLOAK-8954  https://issues.redhat.com/browse/KEYCLOAK-8954)?