KEYCLOAK-9372 update EAP version
keycloak/keycloak-documentation pull request #566
Opened 2019-01-17 18:14 UTC by matthewhelmke

2019-01-18 09:05 UTC, vmuzikar commented
Thanks for the update, @matthewhelmke! Unfortunately, there's more. EAP 7.0 and 7.1 is still mentioned throughout the Securing Applications and Services Guide. Please see e.g. https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/java/jboss-adapter.adoc

2019-01-18 12:32 UTC, matthewhelmke commented
@vmuzikar There were two files I intentionally left the mentions in.

1. /securing_apps/topics/oidc/java/jboss-adapter.adoc
2. /securing_apps/topics/oidc/java/jboss-adapter.adoc

In both, the mentions are within install instructions on a variety of system configurations. Are we not supporting all those configurations any more?

2019-01-18 13:54 UTC, vmuzikar commented
@matthewhelmke I believe, currently is supported 6.4 and 7.2 (and possibly 7.1)? Correct, @pdrozd?

2019-01-18 14:06 UTC, matthewhelmke commented
These are the sections in question.

From `securing_apps/topics/saml/java/jboss_adapter_installation.adoc`:

> ifeval::[{project_product}==true]
> .JBoss EAP 7.1 or newer
> [source]
> ----
> $ cd $JBOSS_HOME
> $ ./bin/jboss-cli.sh -c --file=bin/adapter-elytron-install-saml.cli
> ----
> 
> .JBoss EAP 7.0 and EAP 6
> [source]
> ----
> 
> $ cd $JBOSS_HOME
> $ ./bin/boss-cli.sh -c --file=bin/adapter-install-saml.cli
> ----
> 
> NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-saml.cli`
> even on those versions. However, we recommend to use the newer Elytron adapter.
> 
> endif::[]

From  `securing_apps/topics/oidc/java/jboss-adapter.adoc`:

> ifeval::[{project_product}==true]
> .JBoss EAP 7.1 or newer
> [source]
> ----
> $ ./bin/jboss-cli.sh --file=bin/adapter-elytron-install-offline.cli
> ----
> 
> .JBoss EAP 7.0
> [source]
> ----
> $ ./bin/jboss-cli.sh --file=bin/adapter-install-offline.cli
> ----
> 
> NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-offline.cli`
> even on those versions. However, we recommend to use the newer Elytron adapter.
> 
> NOTE: The offline script is not available for JBoss EAP 6.4
> 
> endif::[]
>

2019-01-18 15:09 UTC, pdrozd commented
@vmuzikar @matthewhelmke Correct, EAP 6.4 and 7.2 is supported. EAP 7.1 is also tested and possibly can be used by customers for some time before they move to 7.2. But I would specify only those two versions 6.4 and 7.2

2019-01-18 15:11 UTC, matthewhelmke commented
Okay, I'll commit an update shortly.

2019-01-18 16:15 UTC, vmuzikar reviewed
@matthewhelmke Thanks!

Just a few notes.

EAP 7.0 is also mentioned here: https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-rpms.adoc

2019-01-18 16:15 UTC, vmuzikar commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> -NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-offline.cli`
I believe the note should remain there.

2019-01-18 17:50 UTC, matthewhelmke commented
Thank you. Both will be fixed in the next commit, coming momentarily.

2019-01-21 09:28 UTC, stianst requested changes

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> +.JBoss EAP 7.2 or newer
This should be 7.1 or newer - installation steps changed in 7.1 (not 7.2)

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> +.JBoss EAP 7.2 or newer
This should be 7.1 or newer - installation steps changed in 7.1 (not 7.2)

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> -NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-offline.cli`
Yes, this should remain

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/oidc/java/jboss-adapter.adoc
> -NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.1 or newer as well, meaning you can use `adapter-install-offline.cli`
This file should just be left unchanged

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/saml/java/jboss-adapter/jboss_adapter_installation.adoc
> +.JBoss EAP 7.2 or newer
This should be 7.1 or newer - installation steps changed in 7.1 (not 7.2)

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/saml/java/jboss-adapter/jboss_adapter_installation.adoc
> +.JBoss EAP 6.4
Leave as is

2019-01-21 09:28 UTC, stianst commented on securing_apps/topics/saml/java/jboss-adapter/jboss_adapter_installation.adoc
> +NOTE: It is possible to use the legacy non-Elytron adapter on JBoss EAP 7.2 or newer as well, meaning you can use `adapter-install-saml.cli`
Leave as is

2019-01-21 09:28 UTC, stianst commented on openshift/topics/get_started.adoc
> +    JBoss EAP 7.2
Use template variable for EAP version. {eap_version} or something like that. Applies to changes below as well.

2019-01-21 12:41 UTC, matthewhelmke commented
@stianst Changes and reversions made.

2019-02-20 10:29 UTC, stianst approved these changes

2019-02-20 10:30 UTC, merged