[KEYCLOAK-9361] Consolidate the OpenShift image documentation for 7.3.0 release
keycloak/keycloak-documentation pull request #572
Opened 2019-01-21 20:43 UTC by iankko

Various changes to polish the OpenShift image documentation for 7.3 release:

- Replace outdated Openshift Primer example cluster install with links to the latest OCP cluster installation procedure,
- Drop duplicate sections (related to keystores, secrets setup etc.),
- Drop unnecessary sections (related to routes, TLS passthrough mode variables)
- Simplify the 'Initial image deployment' `Getting Started` subsection,
- Consolidate the `Tutorials` DB migration section,
- Move the `Binary Builds` tutorial from `Getting Started` to `Tutorials` section

See relevant git commit messages for further details.

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

2019-01-21 20:44 UTC, iankko commented
@matthewhelmke @stianst PTAL (once got a chance)

Thank you, Jan

2019-01-21 20:49 UTC, matthewhelmke commented
I will look at this more closely as soon as I can, but I don't think I will have time to review it all before the 7.3 release tomorrow. However, I should have time to review it before my last day on Friday to try to help get it ready for the first point release later.

2019-01-23 15:05 UTC, matthewhelmke requested changes
This is long and I am pleased to request very few changes. Well done!

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/advanced_concepts.adoc
You actually need both instances of "the" in there: Customizing the Hostname for the {project_name} Server.

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/get_started.adoc
> +==== Deploying the {project_name} Image using Application Template
"...Using the Application Template" <-needs a "the"

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/get_started.adoc
> +===== Deploying the Template via OpenShift Web Console
"...via the OpenShift..."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/get_started.adoc
"...via the OpenShift..."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/tutorials.adoc
> +.. Ensure the *Temporary Password* option is set to *Off* so that it does not prompt for a password change later on, and click *Reset Password* to set the user password. A pop-up window prompts for a
"A pop-up window will prompt you to confirm."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/tutorials.adoc
> +The link:https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-jee-jsp[app-jee-jsp] quickstart requires to configure the adapter, and adapter configuration file (`keycloak.json`) to be pre
"...quickstart requires you to configure..." "...and that the adapter configuration file...is present in the..."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/tutorials.adoc
> +Create main directory for the binary build on the local file system and *deployments/* subdirectory within it. Copy the previously built WAR archives of both the *service-jee-jaxrs* and *app-jee-jsp*
"Create the main directory..."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/tutorials.adoc
> +Location of the standard deployments directory depends on the underlying base image, that was used to deploy the application. See the following table:
"The location of the standard..."

2019-01-23 15:05 UTC, matthewhelmke commented on openshift/topics/tutorials.adoc
> +Specify username and password of the {project_name} user configured earlier (`appuser` / `apppassword`). Click *Log in*. The look of the application changes as detailed in the following image:
"Specify the username..."

2019-01-23 19:24 UTC, matthewhelmke submitted a review, later dismissed
Thank you!

2019-01-23 19:26 UTC, iankko commented on openshift/topics/advanced_concepts.adoc
Thanks, Matt! Fixed (see last commit).

2019-01-23 19:26 UTC, iankko commented on openshift/topics/get_started.adoc
> +===== Deploying the Template via OpenShift Web Console
Fixed.

2019-01-23 19:26 UTC, iankko commented on openshift/topics/tutorials.adoc
> +.. Ensure the *Temporary Password* option is set to *Off* so that it does not prompt for a password change later on, and click *Reset Password* to set the user password. A pop-up window prompts for a
Added your suggestion.

2019-01-23 19:27 UTC, iankko commented on openshift/topics/tutorials.adoc
> +The link:https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-jee-jsp[app-jee-jsp] quickstart requires to configure the adapter, and adapter configuration file (`keycloak.json`) to be pre
Ditto. Fixed both parts.

2019-01-23 19:27 UTC, iankko commented on openshift/topics/tutorials.adoc
> +Location of the standard deployments directory depends on the underlying base image, that was used to deploy the application. See the following table:
This one too.

2019-01-23 19:27 UTC, iankko commented on openshift/topics/tutorials.adoc
> +Specify username and password of the {project_name} user configured earlier (`appuser` / `apppassword`). Click *Log in*. The look of the application changes as detailed in the following image:
Ditto.

2019-01-23 19:28 UTC, matthewhelmke submitted a review, later dismissed
LGTM, thank you!

2019-01-23 19:29 UTC, iankko commented
Addressed all issues (see last commit) & rebased to current master. Thank you for the suggestions!

2019-02-14 14:18 UTC, tanberry commented
Hi all, I'm tagging others in CCS to take a look at where we are with this guide. Jan thank you for all of the months and months that you and Matthew worked on this. 

It sounds like there is still a review needed here and then merge this work, but also a higher-level discussion about what to do with the older xPAS guide. I'll loop in on on the email thread, Jan.

@cwatkins @vikram @ncbaratta

2019-02-20 11:08 UTC, hmlnarik commented
@iankko could you please rebase this PR?

2019-02-20 16:27 UTC, iankko commented
@hmlnarik Fixed the conflict & rebased against current master. Thanks for heads-up!

2019-05-03 10:50 UTC, hmlnarik approved these changes

2019-05-03 10:50 UTC, merged