Update providers.adoc
keycloak/keycloak-documentation pull request #635
Opened 2019-04-09 12:33 UTC by tsabirgaliev

Give some hints on how to setup a Maven project to get started

2019-04-09 12:41 UTC, tsabirgaliev commented
I'm sorry, I can't get rid of empty line at the end, Github UI adds that :(

2019-04-18 19:43 UTC, andymunro commented on server_development/topics/providers.adoc
> +If you want to see list of all available SPIs at runtime, you can check `Server Info` page in admin console as described in <<_providers_admin_console,Admin Console>> section.
Please add "the" before 'list of all available' and 'Server Info' page

2019-04-29 13:56 UTC, stianst requested changes
Not convinced this should be added to docs as it is covered better by QuickStarts. If we want to merge this version of BOM needs to be templated in using variable rather than hardcoded as it is now.

2019-06-07 06:58 UTC, stianst commented
Closing due to lack of feedback

2019-06-07 06:58 UTC, closed without merging