KEYCLOAK-10158 Document certificate identity source and attribute mapper
keycloak/keycloak-documentation pull request #651
Opened 2019-04-30 10:13 UTC by sventorben

Documentation for changes in PR https://github.com/keycloak/keycloak/pull/6026

2019-07-12 11:21 UTC, mposolda submitted a review, later dismissed
@andymunro Do you have a chance to review please?

2019-07-12 12:09 UTC, andymunro requested changes
On line 50, that should be "because" not "cause"

Otherwise looks good.

2019-07-15 05:12 UTC, sventorben commented
@andymunro Fixed.

2019-07-19 13:15 UTC, hmlnarik approved these changes

2019-07-19 13:15 UTC, merged