rhel-8 rpms changes upstream
keycloak/keycloak-documentation pull request #673
Opened 2019-05-30 22:19 UTC by pskopek

https://issues.jboss.org/browse/KEYCLOAK-10362
https://issues.jboss.org/browse/KEYCLOAK-10339
https://issues.jboss.org/browse/KEYCLOAK-10338

2019-05-31 14:00 UTC, andymunro submitted a review, later dismissed

2019-06-05 07:07 UTC, pdrozd requested changes

2019-06-05 07:07 UTC, pdrozd commented on server_installation/topics/installation/installing-rpm.adoc
> + dnf install rh-sso7
It should be "dnf groupinstall rh-sso7" It was wrong in the jira sorry

2019-06-05 12:00 UTC, pdrozd approved these changes

2019-06-05 12:01 UTC, merged