KEYCLOAK-10776 Add info about session length in authnStatement to docs
keycloak/keycloak-documentation pull request #698
Opened 2019-07-11 10:44 UTC by mhajas

2019-07-11 10:48 UTC, hmlnarik commented
Related to keycloak/keycloak#6161

2019-07-11 10:51 UTC, hmlnarik requested changes

2019-07-11 10:51 UTC, hmlnarik commented on server_admin/topics/clients/client-saml.adoc
> +  This is enabled by default value, which means that AuthStatement element will be included in login responses. Notice, that setting this to off
```suggestion
  This is enabled by default which means that `AuthStatement` element will be included in login responses. Note that setting this to off
```

2019-07-11 10:51 UTC, hmlnarik commented on server_admin/topics/clients/client-saml.adoc
> +  will make client side unable to know session length, what will result in timeless session on client side.
```suggestion
  would prevent client from determining maximum session length which could result into never expiring client session.
```

2019-07-11 12:31 UTC, hmlnarik submitted a review, later dismissed

2019-07-11 15:40 UTC, andymunro commented on server_admin/topics/clients/client-saml.adoc
> +  would prevent client from determining maximum session length which could result into never expiring client session.
Suggest adding "the" --- would prevent "the" client from determining "the" maximum....

2019-07-12 06:52 UTC, mhajas commented
Thank you very much for review @andymunro. I added them.

2019-07-24 10:32 UTC, hmlnarik approved these changes

2019-07-29 06:15 UTC, merged