KEYCLOAK-11196 Document the `useNonce` option for JS adapter
keycloak/keycloak-documentation pull request #724
Opened 2019-08-27 10:32 UTC by jonkoops

See: https://github.com/keycloak/keycloak/pull/6272

2019-08-27 11:05 UTC, jonkoops commented
Looks like the external link check is failing, but it seems unrelated to this PR.

2019-09-12 10:06 UTC, stianst requested changes

2019-09-12 10:06 UTC, stianst commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +* useNonce - Adds a https://en.wikipedia.org/wiki/Cryptographic_nonce[cryptographic nonce] to verify that the authentication response matches the request (default is true).
Can you remove the link please and just write cryptographic nonce?

2019-09-12 12:02 UTC, jonkoops commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +* useNonce - Adds a https://en.wikipedia.org/wiki/Cryptographic_nonce[cryptographic nonce] to verify that the authentication response matches the request (default is true).
Done :+1:

2019-09-18 09:29 UTC, stianst approved these changes

2019-09-18 09:29 UTC, stianst commented
Thanks

2019-09-18 09:29 UTC, merged