Update the release notes to give credits to our contributors
keycloak/keycloak-documentation pull request #747
Opened 2019-09-24 13:42 UTC by abstractj

- [KEYCLOAK-11193] Add new  option to JS adapter
- [KEYCLOAK-9786] Secure token and logout endpoint

2019-09-27 12:30 UTC, mhajas requested changes
Just one comment, the change was actually to disable logging and enable it only in case a parameter is set to true

2019-09-27 12:30 UTC, mhajas commented on release_notes/topics/8_0_0.adoc
> +* Added option to disable logging to the console. Thanks to https://github.com/jonkoops[jonkoops]
```suggestion
* Added option to enable/disable logging to the console. Thanks to https://github.com/jonkoops[jonkoops]
```

2019-09-27 18:54 UTC, andymunro submitted a review, later dismissed

2019-10-04 07:00 UTC, mhajas submitted a review, later dismissed

2019-10-09 10:21 UTC, stianst approved these changes

2019-10-09 10:22 UTC, stianst requested changes

2019-10-09 10:22 UTC, stianst commented on release_notes/topics/8_0_0.adoc
> +* Added option to enable/disable logging to the console. Thanks to https://github.com/jonkoops[jonkoops]
This should mention that it is for the JS adapter

2019-10-30 20:01 UTC, abstractj commented
@stianst updated.

2019-10-30 20:12 UTC, andymunro approved these changes

2019-10-31 10:11 UTC, stianst approved these changes

2019-10-31 10:11 UTC, merged