Note
keycloak/keycloak-documentation pull request #762
Opened 2019-10-23 19:31 UTC by andymunro

I moved the note to be after the metadata and changed the asciidoc coding for this note.

2019-10-30 14:54 UTC, stianst commented
Is there a JIRA for this work?

2019-10-30 15:57 UTC, iankko requested changes
@andymunro Hey Andy,

  wondering what's the purpose of this one (since it contains commit from https://github.com/keycloak/keycloak-documentation/pull/759 one too). 

Was the intention to fix just [KEYCLOAK-11783](https://issues.jboss.org/browse/KEYCLOAK-11783) within this one? If that's the case, can you remove the first commit related with other, unrelated ([KEYCLOAK-7010](https://issues.jboss.org/browse/KEYCLOAK-7010)) JIRA?

Thanks, Jan

2019-10-30 17:34 UTC, andymunro commented
Yes, thanks, @iankko,  that was not intentional.  I removed it.

2019-11-07 13:26 UTC, stianst commented on server_installation/topics/operating-mode/crossdc.adoc
> +====
This shouldn't be needed as it's already in techpreview.adoc. Looks like for some reason that is not working.

2019-11-07 13:29 UTC, stianst commented
Closing this - proper PR here: https://github.com/keycloak/keycloak-documentation/pull/775

2019-11-07 13:29 UTC, closed without merging