KEYCLOAK-12125 Update docs regarding SameSite changes
keycloak/keycloak-documentation pull request #824
Opened 2020-01-17 13:19 UTC by mhajas

2020-01-17 14:06 UTC, hmlnarik commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +WARNING: Starting Chrome version 80 (released on February 2020) silent check-sso functionality will work only when SSL / TLS connection is configured on {project_name} side.
```suggestion
WARNING: Starting Chrome version 80 (released on February 2020), silent `check-sso` functionality will work only when SSL / TLS connection is configured on {project_name} side.
```

2020-01-17 14:32 UTC, hmlnarik commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +cookie over SSL / TLS connection configured on {project_name} side. Using insecure connection, may lead to redirecting
```suggestion
cookie over SSL / TLS connection configured on {project_name} side. Using insecure connection may lead to redirecting
```

2020-01-17 14:32 UTC, hmlnarik commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +WARNING: Starting Chrome version 80 (released on February 2020), silent `check-sso` functionality will work only when
```suggestion
WARNING: Starting with Chrome version 80 (released on February 2020), silent `check-sso` functionality will work only when
```

2020-01-17 14:32 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +== SameSite Cookie changes with upcoming Google Chrome update
```suggestion
== SameSite cookie changes with upcoming Google Chrome update
```

2020-01-17 14:32 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +Google chrome starting version 80, will change its default value for SameSite cookie argument to `Lax`. Therefore we
```suggestion
Google Chrome starting with version 80 will change the default value for `SameSite` cookie parameter to `Lax`. Therefore
```

2020-01-17 14:32 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +needed to change some of our cookies (especially those which are used within our Javascript adapter for checking session
```suggestion
changes were required to several {project_name} cookies (especially those which are used within our Javascript adapter for checking session
```

2020-01-17 14:32 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +status using the iframe) to have SameSite argument set to None which requires also setting the argument Secure. This
```suggestion
status using the iframe) to set SameSite parameter to `None`. Please note that this settings also requires setting the Secure parameter, hence
```

2020-01-17 14:32 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +means starting with version 9.0.0 our Javascript adapter will be fully functional only using TLS on {project_name} side.
```suggestion
starting with this version, our Javascript adapter will only be fully functional when using SSL / TLS connection on {project_name} side.
```

2020-01-17 14:53 UTC, hmlnarik commented on release_notes/topics/9_0_0.adoc
> +Google Chrome starting with version 80, will change the default value for `SameSite` cookie parameter to `Lax`.
```suggestion
Starting with version 80, Google Chrome will change the default value for `SameSite` cookie parameter to `Lax`.
```

2020-01-17 15:31 UTC, hmlnarik requested changes
Thanks @mhajas ! Can you please check Travis? The failure seems relevant

2020-01-20 10:24 UTC, hmlnarik submitted a review, later dismissed

2020-01-20 11:16 UTC, abstractj submitted a review, later dismissed

2020-01-20 12:18 UTC, stianst commented
Wonder if this should be listed in 8.0.2 changes instead of 9.0.0, as it will be released in 8.0.2.

2020-01-20 12:18 UTC, stianst reviewed
See previous comment

2020-01-20 21:27 UTC, bigred8982 commented
@stianst Is this change expected to make it into 8.0.2? 

I don't see an issue related to this in the 8.0.2 release - https://issues.redhat.com/projects/KEYCLOAK/versions/12343302

2020-01-22 12:32 UTC, hmlnarik submitted a review, later dismissed

2020-01-22 12:36 UTC, hmlnarik commented
The travis failures are irrelevant to this PR.

2020-01-24 16:03 UTC, andymunro commented on release_notes/topics/8_0_2.adoc
> +Starting with version 80, Google Chrome will change the default value for `SameSite` cookie parameter to `Lax`.
Add "the" before 'SameSIte'

2020-01-24 16:04 UTC, andymunro commented on release_notes/topics/8_0_2.adoc
> +Therefore changes were required to several {project_name} cookies (especially those which are used within our
Add a comma after Therefore

2020-01-24 16:05 UTC, andymunro commented on release_notes/topics/8_0_2.adoc
> +Javascript adapter for checking session status using the iframe) to set `SameSite` parameter to `None`. Please note
Add "the" before session status

Add "the" before 'SameSIte'

2020-01-24 16:06 UTC, andymunro commented on release_notes/topics/8_0_2.adoc
> +that this settings also requires setting the `Secure` parameter, hence starting with this version, our Javascript
Change "our" to "the"

2020-01-24 16:06 UTC, andymunro commented on release_notes/topics/8_0_2.adoc
> +adapter will only be fully functional when using the SSL / TLS connection on {project_name} side.
add "the" before {project_name}

2020-01-24 16:07 UTC, andymunro commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +when the SSL / TLS connection is configured on {project_name} side.
add "the" before {project_name}

2020-01-24 16:08 UTC, andymunro commented on securing_apps/topics/oidc/javascript-adapter.adoc
> +cookie over the SSL / TLS connection configured on {project_name} side. Using insecure connection may lead to redirecting
add "the" before {project_name} and before "insecure."

2020-01-24 16:09 UTC, andymunro requested changes
Looks good apart from the changes I suggested.

2020-01-27 08:21 UTC, mhajas commented
Thank you @andymunro, I updated the PR.

2020-01-30 23:57 UTC, abstractj approved these changes
@stianst @hmlnarik LGTM

2020-01-31 12:05 UTC, merged