KEYCLOAK-12910 Authentication SPI - Secret Question update
keycloak/keycloak-documentation pull request #843
Opened 2020-02-06 16:51 UTC by mabartos

JIRA: [KEYCLOAK-12910](https://issues.redhat.com/browse/KEYCLOAK-12910) Impossible to compile keycloak examples

[PR#6742](https://github.com/keycloak/keycloak/pull/6742)

2020-02-06 19:06 UTC, mposolda submitted a review, later dismissed
@mabartos Thanks!

@andymunro Do you have a chance to review please?

2020-02-06 19:58 UTC, andymunro commented on server_development/topics/auth-spi.adoc
> +which should at least includes type and category of authenticator, displayName and removable item. In this example, the builder
"include" not "includes"

2020-02-06 19:58 UTC, andymunro commented on server_development/topics/auth-spi.adoc
> +Another items of builder are helpText (will be shown to the user on various screens), createAction (the providerID of the required action,
Change "Another" to "Other"

2020-02-06 19:59 UTC, andymunro requested changes
A few minor changes

2020-02-07 07:33 UTC, mabartos commented
@andymunro @mposolda Thanks :)

2020-02-07 12:52 UTC, mposolda approved these changes

2020-02-07 12:52 UTC, merged