KEYCLOAK-13289 Added redirect_url to Node.js logout
keycloak/keycloak-documentation pull request #875
Opened 2020-03-11 08:36 UTC by bender316

2020-03-17 18:52 UTC, abstractj commented on securing_apps/topics/oidc/nodejs-adapter.adoc
> +This parameter is then used as the redirect url of the OIDC logout endpoint.
@bender316 thanks for submitting this. My suggestion is to not only include this paragraph, but also a snippet with examples. What do you think?

2020-03-17 18:52 UTC, abstractj requested changes
@bender316 thanks for submitting this. My suggestion is to not only include this paragraph, but also a snippet with examples. What do you think?

2020-03-23 18:15 UTC, bender316 commented
@abstractj I updated the section a bit with an example.

2020-03-23 21:13 UTC, abstractj approved these changes

2020-03-23 21:13 UTC, abstractj commented
@bender316 thank you. I'm just waiting for Travis, but it looks good to me.

2020-07-02 19:16 UTC, merged