KEYCLOAK-13908: Database Migration to >=9.0.1 fails on MySQL
keycloak/keycloak-documentation pull request #922
Opened 2020-04-24 08:40 UTC by rmartinc

Documentation fix for KEYCLOAK-13908. Finally it was decided that no coding action will be added and only a documentation warning will be added.
Feel free to change anything. I spend a lot of time with these doc PRs and I'm never totally happy with them. :-)

2020-04-24 11:50 UTC, mposolda submitted a review, later dismissed
@rmartinc Thanks! I am adding also Andy as a reviewer of this PR - he is our documentation expert.

@andymunro Do you have a chance to review this please?

2020-04-24 18:25 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +Version 9.0.1 fixes a problem which could create duplicated top level groups in the realm. Nevertheless the existance
existence

2020-04-24 18:26 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +if it is using a H2, MariaDB, MySQL or PostgreSQL database. Before launching the upgrade check if the server contains
comma after upgrade

2020-04-24 18:27 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +duplicated top level groups, for example the following SQL query can be executed at database level to list them:
make "for example..."  a new sentence.

2020-04-24 18:28 UTC, andymunro requested changes
A few changes.

2020-04-25 14:15 UTC, rmartinc commented
> A few changes.

Thanks @andymunro! The three changes you requested are incorporated....

2020-04-27 14:00 UTC, mposolda approved these changes

2020-04-27 14:01 UTC, merged