increase readability
keycloak/keycloak-documentation pull request #935
Opened 2020-05-06 11:02 UTC by FritzOscar

2020-07-01 22:09 UTC, abstractj commented
@andymunro could you please review when you get the chance?

2020-07-02 15:41 UTC, andymunro requested changes
Just one minor change. Thanks.

2020-07-02 15:41 UTC, andymunro commented on server_admin/topics/sessions/offline.adoc
> +This is useful if your application needs to do some "offline" actions on behalf of the user even when she is not online.
Looks good.  However, to make it relatable to men or women, I suggest "that user" in place of "she."

2020-07-02 19:23 UTC, abstractj commented
Thanks Andy. @FritzOscar could you please update your PR based on the considerations here?

2021-11-02 07:38 UTC, closed without merging