KEYCLOAK-13104 Signed and Encrypted ID Token Support : AES 192bit and 256bit key support
keycloak/keycloak-documentation pull request #943
Opened 2020-05-20 09:01 UTC by tnorimat

This PR is for [KEYCLOAK-13104](https://issues.redhat.com/browse/KEYCLOAK-13104) .

2020-05-20 09:11 UTC, tnorimat commented
The tests failed but not relevant to this documentation PR.

```
Running org.keycloak.documentation.test.ServerAdminTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 165.892 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.ServerAdminTest)  Time elapsed: 165.67 sec  <<< FAILURE!
* http://www.haproxy.org/#docs (exception Connect to www.haproxy.org:80 [www.haproxy.org/51.15.8.218] failed: Connection timed out (Connection timed out))
```

2020-05-20 15:03 UTC, mposolda submitted a review, later dismissed
@andymunro Do you have a chance to review this please?

2020-05-28 15:52 UTC, andymunro commented on server_admin/topics/clients/client-oidc.adoc
> +ID token encryption algorithms by CEK are also defined in https://tools.ietf.org/html/rfc7518#section-5.1[JWA] specification. {project_name} supports AES_CBC_HMAC_SHA2 algorithms and AES GCM algorith
add "the" before https:

2020-05-28 15:53 UTC, andymunro requested changes
one minor change

2020-05-29 00:07 UTC, tnorimat commented
@andymunro Thank you for the review. I've revised the document as you suggested.

2020-05-29 06:43 UTC, mposolda approved these changes
@andymunro @tnorimat Thanks for the review and update!

2020-05-29 06:44 UTC, merged