KEYCLOAK-14103 Document setting of SameSite to None for Wildfly/EAP a…
keycloak/keycloak-documentation pull request #949
Opened 2020-06-02 10:24 UTC by mhajas

…nd Tomcat

2020-06-02 10:39 UTC, hmlnarik requested changes

2020-06-02 10:39 UTC, hmlnarik commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +SAML Post binding might be broken in the latest versions of browsers due to changes to the SameSite default value. To
Explain a bit what SameSite is before using it.

2020-06-02 10:39 UTC, hmlnarik commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +The support for this configuration is available in Wildfly from version 19.1.0 and in EAP from versions 7.3.2.GA and
Neither EAP 7.3.2 nor 7.2.9 is available. Refer the reader to EAP documentation for determining when this can be used, or don't reference EAP at all.

2020-06-02 10:39 UTC, hmlnarik commented on securing_apps/topics/saml/java/tomcat-adapter/tomcat-adapter-samesite-setting.adoc
> +SAML Post binding might be broken in the latest versions of browsers due to changes to the SameSite default value. To
Explain a bit what SameSite is before using it.

2020-06-02 11:46 UTC, vmuzikar reviewed
I believe we should add instructions for Jetty too. If we decide to not to do this in this PR, we'll need to create a follow-up JIRA.

2020-06-02 12:15 UTC, vmuzikar reviewed
Two more things.

Should we advice the users to strongly consider the potential security risk that `SameSite=None` brings (especially in Tomcat's case where this setting is global for all cookies)? Like some link to where SameSite is documented with a hint to use OIDC if they don't want to a security issue with SameSite?

Should we add some note that users don't actually need to upgrade their adapter to a newer version just to resolve the SameSite issue? I mean, all we did at the adapter's side is we adde a warning into the log.

2020-06-02 20:13 UTC, andymunro commented on release_notes/topics/11_0_0.adoc
> +Usage of a different value is causing resetting of the container's session with each request to the Keycloak, when
remove "the" before "Keycloak"
Change "Keycloak" to "{project_name}"

2020-06-02 20:13 UTC, andymunro commented on release_notes/topics/11_0_0.adoc
> +the SAML Post binging is used. Refer to following steps for
add "the" before "following steps"

2020-06-02 20:26 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +Browsers are planning to set default value for the `SameSite` attribute for cookies to `Lax`. This means that
Add "the" before "the"
Try to always follow "this" with a noun, so it is clear what "this" refers to.   "This setting"

2020-06-02 20:27 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +cookies will be sent to applications only if the request originates in the same domain. This behavior can affect SAML
Add "the" before "SAML"

2020-06-02 20:27 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +Post binding which may become non-functional. To preserve full functionality of the SAML adapter, it is recommended to
use "we recommend" instead of "it is recommended"  -- it is more active

2020-06-02 20:28 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +set the `SameSite` value to `None` for `JSESSIONID` cookie created by your container. Not doing so may result in
add "the" before `JSESSIONID`

2020-06-02 20:28 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +resetting container's session with each request to {project_name}.
add "the" before "container's"

2020-06-02 20:29 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +To set the `SameSite` value to `None` for `JSESSIONID` cookie in Wildfly/EAP add a file `undertow-handlers.conf`, with
add "the" before JSESSIONID
add a command after EAP

2020-06-02 20:29 UTC, andymunro commented on securing_apps/topics/saml/java/jboss-adapter/jboss-adapter-samesite-setting.adoc
> +following content, to the `WEB-INF` directory of your application.
add  "the" before "following"

2020-06-02 20:30 UTC, andymunro commented on securing_apps/topics/saml/java/tomcat-adapter/tomcat-adapter-samesite-setting.adoc
> +Browsers are planning to set default value for the `SameSite` attribute for cookies to `Lax`. This means that
Please make the same changes as above.

2020-06-02 20:31 UTC, andymunro requested changes
Looks good. Just a few changes suggested.

2020-06-03 11:56 UTC, mhajas commented
Thank you for review @vmuzikar!

> I believe we should add instructions for Jetty too. If we decide to not to do this in this PR, we'll need to create a follow-up JIRA.

I created a follow-up Jira: https://issues.redhat.com/browse/KEYCLOAK-14372

> Two more things.
> 
> Should we advice the users to strongly consider the potential security risk that `SameSite=None` brings (especially in Tomcat's case where this setting is global for all cookies)? Like some link to where SameSite is documented with a hint to use OIDC if they don't want to a security issue with SameSite?
>
> Should we add some note that users don't actually need to upgrade their adapter to a newer version just to resolve the SameSite issue? I mean, all we did at the adapter's side is we adde a warning into the log.

I added both. Let me know if this is what you meant.

2020-06-03 12:56 UTC, mhajas commented
@andymunro Thank you very much for the review. I incorporated all suggestions (I also added some more things based on the review from @vmuzikar). Could you please take a look again?

2020-06-03 13:43 UTC, vmuzikar commented
@mhajas Thanks for the update. Found one last nitpick. "POST" in "Post binding" should be written as capitals (POST binding). Looking at the rest of the guide, we always refer to it as "POST binding", so I think we should be consistent.

2020-06-03 14:51 UTC, mhajas commented
@vmuzikar Thanks, done

2020-06-03 15:01 UTC, vmuzikar commented on release_notes/topics/11_0_0.adoc
> +== SAML Post binding is broken in the latest versions of browsers
One last "Post" ;)
```suggestion
== SAML POST binding is broken in the latest versions of browsers
```

2020-07-01 15:08 UTC, vmuzikar commented
@hmlnarik @mhajas The last thing I'm missing is mentioning the SameSite support in EAP more explicitly, ideally incl. versions. But I understand we cannot mention any version before release. So should we create a follow-up JIRA?

2020-07-03 11:02 UTC, hmlnarik submitted a review, later dismissed

2020-07-14 07:05 UTC, vmuzikar submitted a review, later dismissed
Created [a follow-up JIRA](https://issues.redhat.com/browse/KEYCLOAK-14746) for the EAP versions.

LGTM, thanks @mhajas!

2020-12-14 13:59 UTC, hmlnarik approved these changes

2020-12-14 14:00 UTC, merged