index.html change when web-context is changed
keycloak/keycloak-documentation pull request #955
Opened 2020-06-12 08:47 UTC by shashank-khede

Whenever the web-context is updated we also should make a change in index.html under the welcome-content folder. If we don't do this change then the server throws 404 Not found when we hit the base URL of the server.

2020-07-10 09:15 UTC, vmuzikar requested changes
@shashank-khede Thank you for your contribution! Could you please create a JIRA for this?

I'm not entirely sure this change belongs here. This section of the docs is about CLI and this note describes how to modify a theme. Maybe it's rather a bug and instead of documenting it, we could fix it. :)

@abstractj @douglaspalmer WDYT?

2020-08-12 17:54 UTC, abstractj commented
@ssilvert do you think it makes sense?

2020-08-12 20:45 UTC, ssilvert commented
> @ssilvert do you think it makes sense?

I don't understand the issue.  I just tried it and the welcome page seems to work fine.

2020-08-20 06:18 UTC, vmuzikar commented
@ssilvert I was able to reproduce it before IIRC. I think it's reproducible only when you change the default context, e.g. changing just the host is not enough.

2020-08-26 15:25 UTC, ssilvert commented
We need a JIRA with clear steps to reproduce.  If nobody wants to look into it we will just close the PR.

2020-09-10 13:35 UTC, abstractj commented
@shashank-khede closing it for now. If you would like to create a Jira with clear steps to reproduce the issue, please let us know.

2020-09-10 13:35 UTC, closed without merging