Add upgrading guide pointing out UserModel changes
keycloak/keycloak-documentation pull request #962
Opened 2020-06-19 13:57 UTC by Martin-Idel-SI

Add information about the changes within `UserModel` and describe who could be affected and how to mitigate.

Connects to https://github.com/keycloak/keycloak/pull/7080

2020-06-22 09:33 UTC, mposolda submitted a review, later dismissed
@Martin-Idel-SI Thanks!

@andymunro Do you please have a chance to review this PR?

2020-06-22 19:19 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +If a database contains users with custom attributes of that exact name, the custom attributes will need to be migrated before upgrading (this is not done automatically). Otherwise, they will not be r
Change " upgrading (this is not done automatically)"

to  "upgrading. This migration does not occur automatically."

2020-06-22 19:22 UTC, andymunro commented on upgrading/topics/keycloak/changes.adoc
> +This implies, that the `username` can now also be accessed and set via `UserModel.getFirstAttribute(UserModel.USERNAME)` (and similar for the other fields).
Change "This implies" to "This situation implies"
Change "(and similar for the other fields)." to "Similar implications exist for other fields."

2020-06-22 19:26 UTC, andymunro requested changes
Thanks, Marek.  A couple of minor changes.

2020-06-23 08:51 UTC, Martin-Idel-SI commented
@andymunro Thanks, I always get carried away with using brackets when they are hardly ever appropriate... :-D

Updated with your suggestions.

2020-06-25 12:40 UTC, mposolda approved these changes
@andymunro @Martin-Idel-SI Thanks for the review and updates!

2020-06-25 12:51 UTC, merged