KEYCLOAK-14758 reorganized Getting Started files for reuse
keycloak/keycloak-documentation pull request #982
Opened 2020-07-20 21:08 UTC by andymunro

@lhanusov, @pskopek  I made some changes related the need to make the topics in this document more resuable.

- Renamed files and directories to match Red Hat standards to simplify reuse.
- Consolidated duplicate SSO/Keycloak files into the images directory

2020-07-27 15:59 UTC, ASzc requested changes
Seems like all the content has been moved ok. I can't see anything that didn't make it into the post-reorg files somewhere.

One issue with the use of a hardcoded product version, see the comment.

2020-07-27 15:59 UTC, ASzc commented on getting_started/topics/standalone/proc-installing-server-product.adoc
> +$ tar -xvzf rh-sso-7.4.0.tar.gz
Why replace the SSO version variable with a hardcoded version? That seems like it'd introduce more maintenance work.

Looking at document-attributes-product, I see project_version is `7.4.0.GA`, so maybe we need to add `project_versionFiles` as `7.4.0`?

2020-07-27 18:55 UTC, andymunro commented
Thanks, @ASzc.  I actually had an attribute I was using for this situation in a different PR.  I have applied it here.  

Thanks for checking.   Looks like @pskopek will be able to get this into 7.4.2, which is great.

2020-07-28 16:42 UTC, ASzc submitted a review, later dismissed
@abstractj LGTM

2020-07-28 17:32 UTC, abstractj commented
@pskopek would you like to review, prior to merge?

2020-07-29 15:04 UTC, pskopek submitted a review, later dismissed
LGTM!

2020-07-29 15:46 UTC, andymunro commented
@pskopek Thanks.  Is it okay to cherry-pick this for prod or do I need to wait till it merged?

2020-08-04 14:35 UTC, andymunro commented
@pskopek Please apply this PR first: https://github.com/keycloak/keycloak-documentation/pull/973

2020-08-05 13:59 UTC, abstractj commented
@andymunro could you please resolve the conflicts so we can get it merged?

2020-08-05 18:18 UTC, andymunro commented
@abstractj Can you check this again now.

2020-08-05 19:27 UTC, pskopek approved these changes
LGTM!

2020-08-05 20:36 UTC, merged